### ISSUE TITLE
ConfigInjectionBean not registered for javax.inject.Provider<T> 

### ISSUE THREAD

**Issue by mkouba** [smallrye/smallrye-config#101]
A simple reproducer: comment out the [injection point in ProviderBean](https://github.com/smallrye/smallrye-config/blob/master/testsuite/extra/src/test/java/io/smallrye/config/test/provider/ProviderBean.java#L35-L37) and the `ProviderTest#testDirectInjection()` test method. `ProviderTest` will fail with `UnsatisfiedResolutionException`. Note that `ConfigInjectionBean` is never registered for a parameterized type.

**Comment by mkouba** [comment]
Also note that SM should not register the custom bean for `Provider` which is handled automatically by a CDI container.

**Comment by dmlloyd** [comment]
I can confirm that this problem still exists, but I'm not really sure how to fix it TBH.  Is there something we have to add to `io.smallrye.config.inject.ConfigProducer`?

**Comment by mkouba** [comment]
@dmlloyd I don't remember the details ;-). I'll have to look at the test tomorrow...

**Comment by mkouba** [comment]
Ok, so for custom types (`io.smallrye.config.test.provider.Email` in this case) we can't use a CDI producer because the set of custom types is not known before the app starts. That's why we analyze all injection points annotated with `ConfigProperty` and register a custom `ConfigInjectionBean` [here](https://github.com/smallrye/smallrye-config/blob/master/implementation/src/main/java/io/smallrye/config/inject/ConfigExtension.java#L65-L83). 

The problem is that SM completely ignores parameterized types. If `Email` was `Email<T>` it wouldn't work.

The `io.smallrye.config.test.provider.ProviderTest` passes because `ProviderBean` declares two injection points: `Email` and `Provider<Email>`. The first one triggers a custom bean registration and the second one is satisfied by the same bean.

The other [comment](https://github.com/smallrye/smallrye-config/issues/101#issuecomment-490045291) means that `javax.inject.Provider` should be treated specially because `javax.enterprise.inject.Instance extends Provider` and so the CDI container provides a bean for all `Provider` injection points.

I can try to send a PR that will handle at least the `Provider` and `Instance` injection points correctly.

NOTE: In Quarkus, this is handled differently (not sure if better) because there is no CDI extension.
