### ISSUE TITLE
StringUtil#split omits backslashes in property values

### ISSUE THREAD

**Issue by Pepo48** [smallrye/smallrye-config#1033]
After we [replaced the deprecated](https://github.com/keycloak/keycloak/pull/21869/files) `quarkus.http.ssl.certificate.file` and `quarkus.http.ssl.certificate.key-file` properties with the new plural form counterparts, [a Windows specific issue report was filed in the Keycloak repository](https://github.com/keycloak/keycloak/issues/23217).

In the case of `ssl-certificate-*files` properties Keycloak just consumes the Quarkus properties and exposes them further as is, there is no additional logic, nor validation. This makes me believe that this rather bug on Quarkus/SmallRye side.

I actually debugged the issue and I tracked it down to the [StringUtil's split method](https://github.com/smallrye/smallrye-config/blob/main/common/src/main/java/io/smallrye/config/common/utils/StringUtil.java#L35). The Windows platform behaviour is following:
<img width="1054" alt="image" src="https://github.com/smallrye/smallrye-config/assets/12138171/93da9024-7d65-4ea9-bbb5-c5bdeb4eee31">
As you can see, the way the matcher pattern is designed now, it omits backslashes, which then results to the `NoSuchFile` Keycloak issue mentioned above.

**How to reproduce?**
The following demo test can be added to StringUtilTest.java:
```
void mixedWindowsAndUnixPath() {
    String text = "C:\\Program Files\\quarkus/extensions/example.java";
    assertEquals("C:/Program Files/quarkus/extensions/example.java", StringUtil.split(text)[0]);
}
```

**Solution**
Either we can preemptively normalize path values in a way `converted = converter.convert(configValue.getValue().replace("\\,", "/"));`. Alternatively we can adjust the pattern in StringUtil.

Or we can workaround this on the Keycloak side ([I already have a proposal](https://github.com/keycloak/keycloak/pull/24080/files)) in case that this won't be considered as a bug.

Let me know your thoughts. I can definitely help with providing a PR.

Thanks.

**Comment by dmlloyd** [comment]
The backslash character acts as an escape character for delimiting list items in the list converter, to allow items to contain commas. If you want a literal backslash then you will need another layer of escapes (that is, four backslashes instead of two).

**Comment by radcortez** [comment]
Also, please check https://github.com/smallrye/smallrye-config/blob/b9ad8b3369ffac72c01bdc6e7275672e0d718079/common/src/test/java/io/smallrye/config/common/utils/StringUtilTest.java#L28 for some examples.

**Comment by Pepo48** [comment]
Thanks guys for the prompt replies.

Should then EpressionConfigSourceInterceptor respect these rules. I probably didn't stress it enough, but the original Keycloak issues is related to env variable expansion. The ExpressionConfigSourceInterceptor seems to return value in the following format:
<img width="955" alt="image" src="https://github.com/smallrye/smallrye-config/assets/12138171/000dd53b-2ffc-4698-82c9-9398ff0711a9"> 
with two backslashes, which then StringUtils wrongly considers to be a delimiter.

Shouldn't the expansion instead of the `C:\\Users\\hudson\\IdeaProjects\\keycloak\\quarkus\\server\\target/kc` produce `C:\\\\Users\\\\hudson\\\\IdeaProjects\\\\keycloak\\\\quarkus\\\\server\\\\target/kc` or simply the Unix way (modern Windows systems can understand the format)`C:/Users/hudson/IdeaProjects/keycloak/quarkus/server/target/kc`? Or am I still missing something?

Thanks for your time.

**Comment by Pepo48** [comment]
The question is whether you guys consider this as a valid issue/enhancement that deserves more attention? If not, we can probably proceed with an workaround on our end (although we typically try to avoid it if possible). 

Purely from the Keycloak perspective it has an importance already, since Keycloak is commonly used on the Windows platform.

**Comment by radcortez** [comment]
Feel free to send a PR, or I can have a look when I find some time.

**Comment by dmlloyd** [comment]
Another possible solution might be to (optionally?) change the nature of property expansion so that it is done as a part of the conversion process. This might allow the list converter to expand the list before properties are replaced. A negative effect of this solution is that it would prevent property expansion from being able to expand *into* a list value with embedded separators: in other words, `foo.list=${baz}`/`baz=a,b,c,d` for example would create a list with one item instead of a list of four items.

**Comment by radcortez** [comment]
@Pepo48 btw, how are you retrieving the configuration? programmatically? with a mapping? an alternative could be to provide your own customer Converter.

**Comment by antsfiles** [comment]
Hi, I'm having this issue too when using a env variable or system property in expression on Windows:

```properties
my-paths=${java.io.tmpdir}/dir/file1,${java.io.tmpdir}/dir/file2,
```
```java
    @Inject
    @ConfigProperty(name = "my-paths")
    List<String> myPaths;

    @Inject
    @ConfigProperty(name = "my-paths")
    String myPathsString;
```
`myPaths` will be C:UsersmeAppDataLocalTemp/dir/file1 and C:UsersmeAppDataLocalTemp/dir/file2

`myPathsString` will be C:\Users\me\AppData\Local\Temp/dir/file1,C:\Users\me\AppData\Local\Temp/dir/file2

I wonder how to configure the expression to consider the returned value of *java.io.tmpdir* as a path.
:-(

**Comment by antsfiles** [comment]
I did a workaround that seems to work for my case:

```java
import jakarta.annotation.Priority;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import io.smallrye.config.ConfigSourceInterceptor;
import io.smallrye.config.ConfigSourceInterceptorContext;
import io.smallrye.config.ConfigValue;
import io.smallrye.config.Priorities;

@Priority(Priorities.APPLICATION)
public class WindowsPathEscapeConfigSourceInterceptor implements ConfigSourceInterceptor {

    private static final Logger LOGGER = LoggerFactory.getLogger(WindowsPathEscapeConfigSourceInterceptor.class);

    @Override
    public ConfigValue getValue(ConfigSourceInterceptorContext configSourceInterceptorContext, String s) {

        ConfigValue configValue = configSourceInterceptorContext.proceed(s);
        if (configValue != null && configValue.getValue() != null && configValue.getValue().length() > 2
                // Windows path ':\' must use "/"
                && configValue.getValue().charAt(1) == ':' && configValue.getValue().charAt(2) == '\\') {
            configValue = configValue.withValue(configValue.getValue().replaceAll("\\\\", "/"));
            LOGGER.debug( "{} : {}", s, configValue.getValue());
        }
        return configValue;
    }

}
```

**Comment by radcortez** [comment]
Great :)
