### ISSUE TITLE
Add the ability to generate equals and hashcode for @ConfigMapping

### ISSUE THREAD

**Issue by ia3andy** [smallrye/smallrye-config#1067]
Currently, it's possible to generate toString as explained here: 
https://smallrye.io/smallrye-config/Main/config/mappings/#tostring

But there is nothing for equals and hashcode. 

The use case is for Quarkus extension config, without this, it's very ugly to deal with equals as shown in this PR:
https://github.com/quarkiverse/quarkus-quinoa/pull/594

When this is done we should update the Quarkus writing extension guide to mention this.

**Comment by ia3andy** [comment]
cc @radcortez

**Comment by dmlloyd** [comment]
This relates to #1001 since those generated interfaces also need equals/hashCode, and should share as much code as possible.

**Comment by ia3andy** [comment]
@radcortez any update on this?

**Comment by radcortez** [comment]
Not yet... sorry @ia3andy. Let me try to prioritize this.
