### ISSUE TITLE
maven build fails for 3.5.1 and 3.5.1-SNAPSHOT.

### ISSUE THREAD

**Issue by chainhead** [smallrye/smallrye-config#1078]
I want to make use of [Secret Keys](https://smallrye.io/smallrye-config/Main/config/secret-keys/). I am using this dependency in my `pom.xml`.

```xml
<!-- https://mvnrepository.com/artifact/io.smallrye.config/smallrye-config-crypto -->
<dependency>
    <groupId>io.smallrye.config</groupId>
    <artifactId>smallrye-config-crypto</artifactId>
    <version>3.5.1</version>
</dependency>
```

However, `mvnw clean package` fails with long list of URLs and this message towards the end.

```bash
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] : io.smallrye.config.SecretKeysHandlerFactory$LazySecretKeysHandler
```

What am I missing?

```bash
./mvnw -v
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: C:\Users\nages\.m2\wrapper\dists\apache-maven-3.8.6-bin\67568434\apache-maven-3.8.6
Java version: 21.0.1, vendor: Oracle Corporation, runtime: C:\Users\nages\bin\graalvm-jdk-21.0.1+12.1
Default locale: en_IN, platform encoding: UTF-8
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
```

```bash
java -version
java version "18.0.2.1" 2022-08-18
Java(TM) SE Runtime Environment (build 18.0.2.1+1-1)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)
```

**Comment by radcortez** [comment]
Any chance you can provide a reproducer? I've tried putting that in an empty project and it worked fine for me, so maybe something else is interfering.

**Comment by chainhead** [comment]
This is my complete POM.

```xml
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-kafka-streams</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-health</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
<!-- https://mvnrepository.com/artifact/io.smallrye.config/smallrye-config-crypto -->
<dependency>
    <groupId>io.smallrye.config</groupId>
    <artifactId>smallrye-config-crypto</artifactId>
    <version>3.5.2</version>
</dependency>
  </dependencies>
```

**Comment by radcortez** [comment]
Which Quarkus version?

I suspect that you are trying to update SR Config in Quarkus manually with a version that Quarkus does not support. Minor versions are usually ok, but some major versions may require adjustments in the Quarkus code. This is the case with SR Config 3.5.x, which requires Quarkus 3.7.x, which has not been released yet.

**Comment by chainhead** [comment]
That's probably the case @radcortez . So, with the current Quarkus version, which version of SR should I use?

**Comment by radcortez** [comment]
If you are using Quarkus 3.6.x, please use SR Config 3.4.4.

If you are only interested in the `smallrye-config-crypto`, this one is managed by the Quarkus BOM: https://github.com/quarkusio/quarkus/blob/16120e9442f15f0a7479bbe112623b7a4364ef9a/bom/application/pom.xml#L3742-L3746, so you can omit the version to always get the right dependency.

If you need other dependencies like the `smallrye-config-jasypt`, you need to use the Quarkiverse Config Extensions: https://github.com/quarkiverse/quarkus-config-extensions. Unfortunately, Jasypt cannot be used as is with the native image and requires some adjustments.
