### ISSUE TITLE
Profiles from ‘late sources’ are not found

### ISSUE THREAD

**Issue by rodcheater** [smallrye/smallrye-config#1160]
Consider an application with `smallrye-config-source-file-system` on the class path, with `SMALLRYE_CONFIG_SOURCE_FILE_LOCATIONS` set in the environment to a directory with a `smallrye.config.profile` file in that directory. The profile mentioned in that file is not added to the list of profiles.

**Comment by radcortez** [comment]
This is expected.

SmallRye Config requires the profile resolution before loading any sources with `SMALLRYE_CONFIG_SOURCE_FILE_LOCATIONS`. Without the profile at this stage, we cannot determine which sources are primary sources or profile-aware sources from a location, so the profile has to be set from one of the primary sources (system properties, environment variables, or custom user source).

This is not clear in the documentation, so I'll update that:
https://smallrye.io/smallrye-config/3.8.1/config/profiles/

**Comment by rodcheater** [comment]
Yup, updating the documentation would be great. 👍
