### ISSUE TITLE
SecuritySupport licence header (legal question)

### ISSUE THREAD

**Issue by senivam** [smallrye/smallrye-config#117]
Hello, 

Just a question - why SecuritySupport has different license header than all others sources in the repository? 

Question is raised due to legal compatibility while using SmallRye config in other open source projects (which requires PLS or CQ).

**Comment by jmesnil** [comment]
@senivam that was an error of mine (I created the file with the wrong IDE settings).
I've fixed it and apply the Apache license to that file.

Thanks for the report!

**Comment by senivam** [comment]
@jmesnil thank you for the very quick reaction I appreciate that

**Comment by jansupol** [comment]
@jmesnil Can we expect a new release with this having fixed soon?
