### ISSUE TITLE
Default config sources?

### ISSUE THREAD

**Issue by jakub-bochenski** [smallrye/smallrye-config#1228]
> By default, SmallRye Config reads configuration properties from multiple configuration sources (by descending ordinal):

    (400) System properties
    (300) Environment variables
    (295) .env file in the current working directory
    (260) application.properties in config folder, located in the current working directory
    (250) application.properties in the classpath
    (100) MicroProfile Config configuration file META-INF/microprofile-config.properties in the classpath

https://smallrye.io/smallrye-config/Main/config/getting-started/

But when I build it with 
```
 new SmallRyeConfigBuilder()
        .addDefaultInterceptors()
        .addDefaultSources()
```

I see it's only using 3 sources:
```
DEBUG [main] io.smallrye.config - SRCFG01006: Loaded ConfigSource SysPropConfigSource with ordinal 400
DEBUG [main] io.smallrye.config - SRCFG01006: Loaded ConfigSource EnvConfigSource with ordinal 300
DEBUG [main] io.smallrye.config - SRCFG01006: Loaded ConfigSource DefaultValuesConfigSource with ordinal -2147483648
```

EDIT: If that file is present I also see
```
DEBUG [main] io.smallrye.config - SRCFG01006: Loaded ConfigSource PropertiesConfigSource[source=file:/app/resources/META-INF/microprofile-config.properties] with ordinal 100
```

**Comment by dmlloyd** [comment]
The `.env` and `application.properties` are Quarkus-specific and probably should not be called out in the SmallRye docs (unless we make it clear that this is specific to Quarkus).

**Comment by jakub-bochenski** [comment]
Yeah those 3 appear to be missing from io.smallrye.config.SmallRyeConfigBuilder#getDefaultSources
```
(295) .env file in the current working directory
(260) application.properties in config folder, located in the current working directory
(250) application.properties in the classpath
```

**Comment by radcortez** [comment]
The sources are only included if their backing files are found. Try adding an `application.properties` to the classpath.

Here, you can also check that the sources are being added when you call `addDefaultSources`:

https://github.com/smallrye/smallrye-config/blob/3bb973af5d2f535ec80f0dd8df27006f6bda08e4/implementation/src/main/java/io/smallrye/config/SmallRyeConfigBuilder.java#L197-L220

**Comment by jakub-bochenski** [comment]
@radcortez  that is not true for any released version https://github.com/smallrye/smallrye-config/blob/3.9.1/implementation/src/main/java/io/smallrye/config/SmallRyeConfigBuilder.java

**Comment by radcortez** [comment]
Yes, it was added in `3.9.0`. 

These are the docs from the previous version:
https://smallrye.io/smallrye-config/3.8.3/config/getting-started/

**Comment by jakub-bochenski** [comment]
I guess no issue here after all?

**Comment by radcortez** [comment]
Lools like it :)

**Comment by radcortez** [comment]
By the way, I added this recently to make it more consistent with the Quarkus default sources.
