### ISSUE TITLE
(discussion) best way to override properties from ENV ?

### ISSUE THREAD

**Issue by laurentperez** [smallrye/smallrye-config#1241]
Hi

I'm looking into possibility of overriding my quarkus application.properties file using `${user.dir}/application.properties` or any `${custom.env.variable}/application.properties`

Spring has the concept of a [PropertyPlaceholderConfigurer](https://github.com/spring-projects/spring-framework/blob/main/spring-beans/src/main/java/org/springframework/beans/factory/config/PropertyPlaceholderConfigurer.java) which can be subclassed for this kind of use case, with NEVER, FALLBACK or OVERRIDE support.

Does smallrye config provide some class equivalent for custom resolution and override of properties ?

ty

**Comment by radcortez** [comment]
SmallRye Config works by layering sources by ordinal and overriding each configuration property, meaning that sources with higher ordinals will override sources with lower ordinals per configuration property. Example:

```properties
#system.properties - ordinal 400
foo=system
```

```
#application.properties - ordinal 250
foo=properties
bar=properties
```

The value `foo` is `system`, and the value `bar` is `properties`. 

SmallRye Config monitors the `${user.dir}/config` for `application.properties:
https://smallrye.io/smallrye-config/3.9.1/config/getting-started/

Or you can use `smallrye.config.locations` for additional places to look for:
https://smallrye.io/smallrye-config/3.9.1/config/configuration/
