### ISSUE TITLE
Cannot deploy configsource-properties in payara 5.192

### ISSUE THREAD

**Issue by markusweisssiemens** [smallrye/smallrye-config#127]
Hi @phillip-kruger , I've found the reason for the issue:
https://github.com/microprofile-extensions/config-ext/issues/18
if you're still interested:
Under Windows all the config extensions which use the AbstractUrlBasedSource as base class are failing to deploy because of the getName() implementation. As this is returning the class prefix and the url it's returning something like PropertiesConfigSource_file:/D:/temp/application.properties.enabled and in the PayaraConfig class this name is used to query the value:
`
private String getValue(String propertyName) {

        String result = null;
        for (ConfigSource configSource : configSources) {
            result = configSource.getValue(propertyName);
            if (result != null) {
                break;
            }
        }
        return result;
    }`
As payara has a build in configsource: fish.payara.nucleus.microprofile.config.source.SecretsDirConfigSource 
which has the following line of code in the getValue method:
`Path path = Paths.get(secretsDir.toString(), property);` and the property is the name provided above which leads to an exception (java.nio.file.InvalidPathException: Illegal char <:> at index 35: secrets\PropertiesConfigSource_file:/D:/temp/application.properties.enabled) for loading the config sources and therefore the deployment fails.

If you just change the getName() method of the AbstractUrlBasedSource it's working.

**Comment by phillip-kruger** [comment]
@markusweisssiemens -awesome, i'll fix that. Thanks

**Comment by radcortez** [comment]
I believe this is not relevant anymore. If this is not the case, please reopen the issue. Thank you!
