### ISSUE TITLE
ConfigSource.onAttributeChange

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-config#140]
In looking at the implementations for the internal `ConfigSource` types we provide, should we be overriding the `onAttributeChange` method?

The default implementation returns "UNSUPPORTED", when I think it makes more sense for some of ours, such as environment and system properties, to be "IMMUTABLE".

**Comment by jmesnil** [comment]
Most of our internal config sources return `UNSUPPORTED` because they do not check for attribute changes and report them.

We have a few that also returns `IMMUTABLE`:
* EnvConfigSource
* PropertiesConfigSource read from an URL

**Comment by kenfinnigan** [comment]
That's what I mean. I took a look at `EnvConfigSource` and `PropertiesConfigSource` and couldn't see the method being overridden to return `IMMUTABLE`

**Comment by jmesnil** [comment]
ah sorry, I should have said that it's done in the smallrye-config-1.4 branch (that depends on SNAPSHOT of microprofile-config):  https://github.com/smallrye/smallrye-config/blob/smallrye-config-1.4/implementation/src/main/java/io/smallrye/config/EnvConfigSource.java#L80

This API is a new feature of mp-config that does not exist in mp-config 1.3 (that smallrye-config master branch uses)

**Comment by kenfinnigan** [comment]
Doh! Sorry about that
