### ISSUE TITLE
Kubernetes ConfigMap ConfigSource

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-config#145]
We need a `ConfigSource` for Kubernetes ConfigMaps.

Can use https://github.com/jamesfalkner/microsweeper-demo/blob/master/src/main/java/com/example/microsweeper/openshift/ConfigMapConfigSource.java as a starting point

**Comment by jmesnil** [comment]
Another approach is to use the existing [DirConfigSource](https://github.com/smallrye/smallrye-config/blob/master/implementation/src/main/java/io/smallrye/config/DirConfigSource.java#L31) that reads from the directory mapped to a ConfigMap.

**Comment by kenfinnigan** [comment]
That requires more configuration when deploying right?

**Comment by jmesnil** [comment]
I'm not sure about that.

If you use the DirConfigSource, you need to know the path that the ConfigMap maps to.
Using k8s API to query the ConfigMap also needs configuration (the namespace and name of the config map at least).

Related thought about that: regardless of the chosen implementation, something to consider when dealing with ConfigMaps is whether the whole ConfigMap should be read at boot time (making the config immutable) or if the config map is read every time a config is fetch.

In its current state, the DirConfigSource scans the config map at boot time making its content immutable.

**Comment by Ladicek** [comment]
Also for reading the ConfigMap through the API, you need permissions that you don't have by default.

**Comment by kenfinnigan** [comment]
Need to evaluate whether there's a benefit to this, or not really

**Comment by radcortez** [comment]
I've document and added a sample on how to use the `FileSystemConfigSource` to read the Kubernetes Config Map.

The only benefit I see to integrate directly with the K8s API is if we want to provide a dynamic Config Source. 

For now, I'll close this and if we get the request, we can implement it.
