### ISSUE TITLE
1.3.10 started returning Optional[false] for non existent boolean properties

### ISSUE THREAD

**Issue by jmartisk** [smallrye/smallrye-config#176]
In 1.3.9, `config.getOptionalValue("NON_EXISTENT_PROPERTY", Boolean.class)`, returns `Optional.empty`

In 1.3.10, the same call started returning `Optional[false]` instead. This is a backward incompatible change in behavior and is not consistent with the behavior for types other than boolean, for which this call still returns `Optional.empty`.

**Comment by Ladicek** [comment]
This also affects SmallRye Fault Tolerance: https://github.com/smallrye/smallrye-fault-tolerance/pull/134

**Comment by kenfinnigan** [comment]
Thoughts @dmlloyd?

**Comment by dmlloyd** [comment]
I also just encountered this bug and I see the cause. My fault!

**Comment by dmlloyd** [comment]
Here's the fix: #177 

Sorry again!
