### ISSUE TITLE
Create Releasenotes

### ISSUE THREAD

**Issue by svenhaag** [smallrye/smallrye-config#194]
Maybe I missed something but it seems there are not release notes whatsoever?

**Comment by kenfinnigan** [comment]
To date, we haven't been creating them.

What would you expect to see in them?

**Comment by svenhaag** [comment]
added, changed, removed features/bugs, braking changes (migration notes), ....

**Comment by kenfinnigan** [comment]
Are you using this project directly?

As usually a lot of that would be handled by a runtime that uses this project

**Comment by svenhaag** [comment]
Yes I use it directly. Some changes are just not obvious like the nullified list when using defaultValue="" (this change was from 3.9.1 to 4.1.1).

**Comment by radcortez** [comment]
Hi,

We are now tracking our releases with Milestones:
https://github.com/smallrye/smallrye-config/milestone/2?closed=1

So you can follow what is going to happen on each release. We hope to include this information on the release notes as well.

Is this what you are looking for?

**Comment by svenhaag** [comment]
That's create. Initially I thought about a CHANGELOG.md for instance, but this is even better I think.

**Comment by radcortez** [comment]
Plus, is the next release, we will populate notes here:
https://github.com/smallrye/smallrye-config/releases

It would look something like this:
https://github.com/quarkusio/quarkus/releases

**Comment by svenhaag** [comment]
Perfect! Thank you.

**Comment by radcortez** [comment]
Closing this one then. Cheers!

**Comment by radcortez** [comment]
Here you can check the release notes for the latest release:
https://github.com/smallrye/smallrye-config/releases/tag/1.6.0
