### ISSUE TITLE
Clean up CDI @ConfigProperty rules

### ISSUE THREAD

**Issue by dmlloyd** [smallrye/smallrye-config#195]
The rules for `@ConfigProperty` are a bit sketchy.  In particular the following points need to be addressed:

* Non-`Optional` properties which have an explicit `defaultValue` of `""` will generally report an error when the configuration is read, if the property is not supplied.  In other words, this causes the property to be explicitly required.  However given that the default `defaultValue` for most values (i.e. non-primitives) is already `""`, it's not needed in most cases.
* It should be made abundantly clear that under no normal circumstances should a config property ever be set to `null`.  This is a compatibility change in some certain cases.

**Comment by kenfinnigan** [comment]
Is this meant to be a spec issue?

**Comment by dmlloyd** [comment]
No, we have implementation issues beyond the spec.  But once we get this behavior stabilized, we should compare with the spec and update it as needed.

**Comment by dmlloyd** [comment]
This is fixed by #209 and #212.
