### ISSUE TITLE
Add Interceptor Mechanism for Resolving

### ISSUE THREAD

**Issue by svenhaag** [smallrye/smallrye-config#198]
Hi,

in DeltaSpike there is a mechanism that replaces keys contained in `${}`, see: https://deltaspike.apache.org/documentation/configuration.html#VariableReplacementinConfiguredValues

A similar thing was reverted recently for unknown reason, see: https://github.com/smallrye/smallrye-config/pull/37.

A more advanced mechanism is also present in the Spring framework, where additionally there can be a default value, see: https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/core.html#beans-using-propertysource.

Please add this placeholder replacing mechanisms and support default values like so: `myKeyValue = ${key.to.use:defaultValue}`

If all of that is to specific, there should be a mechanism to intercept the config property resolving. So, before finally returning the resolved property value, execute some custom interceptors or filters (CDI based).

**Comment by dmlloyd** [comment]
We have this in Quarkus (not in SmallRye Config yet).  We've been working on getting variable expression support in the upstream specification, and in the mean time, the SmallRye Common project has been created to provide a home for the variable expander that we use there.  So this is slowly making its way in.  See also eclipse/microprofile-config#396 and eclipse/microprofile-config#405.

**Comment by radcortez** [comment]
Discussion about a prototype to work as foundations to support property replacement and other things done here:
https://github.com/eclipse/microprofile-config/issues/526

Plan is to implement this in SmallRye.

**Comment by radcortez** [comment]
@dmlloyd now that we have the interceptor support, this becomes way easier to implement.

For the actual replacement code, should we copy your Expression code from Wildfly Common into the common module? I guess that we don't want to add the dependency directly.

**Comment by dmlloyd** [comment]
No, I'll release SmallRye Common and we can depend on `smallrye-common-expression`.  Ken has been asking me to make some progress in this area anyway.

**Comment by radcortez** [comment]
Ok.
