### ISSUE TITLE
patternValidatingConverter never used?!

### ISSUE THREAD

**Issue by svenhaag** [smallrye/smallrye-config#199]
It seems these methods are never used. What are there purpose?

https://github.com/smallrye/smallrye-config/blob/bf7bc83cca1efa9ec2027642a70fe829a039519d/implementation/src/main/java/io/smallrye/config/Converters.java#L376

**Comment by kenfinnigan** [comment]
What do you mean never used?

Just because they're not used within SmallRye Config doesn't mean they're not used in downstream projects.

I believe these are used in Quarkus. @dmlloyd could confirm

**Comment by dmlloyd** [comment]
These methods can be used by users to provide extra levels validation.  They're intended to be used with the `Config#getValue(String,Converter<T>)` family of methods.

**Comment by svenhaag** [comment]
Thanks for clarification.
