### ISSUE TITLE
Use ordered properties so properties are in the order specified

### ISSUE THREAD

**Issue by davsclaus** [smallrye/smallrye-config#210]
It would be good if smallrye would use ordered properties so when you for example get the property keys then they are in the order they were added, and so on.

At Apache Camel we hit a problem with JDK 8 vs 11 issue because the Properties / Hashtable implementation of the JDK is changed
https://issues.apache.org/jira/browse/CAMEL-14268

We had this problem too with Apache Camel and we have a ordered properties implementation so they are always in the same order
https://github.com/apache/camel/blob/master/core/camel-util/src/main/java/org/apache/camel/util/OrderedProperties.java

In Smallrye there is a couple of places where you use unordered properties/maps etc
https://github.com/smallrye/smallrye-config/blob/master/common/src/main/java/io/smallrye/config/common/utils/ConfigSourceUtil.java#L54
https://github.com/smallrye/smallrye-config/blob/master/implementation/src/test/java/io/smallrye/config/KeyValuesConfigSource.java#L26

And some places you are using ordered maps such as linked
https://github.com/smallrye/smallrye-config/blob/master/common/src/main/java/io/smallrye/config/common/MapBackedConfigSource.java#L63

Sorry for this short issue ticket. I am happy to discuss further.

**Comment by dmlloyd** [comment]
In general I'm not opposed to this, however the `ConfigSource` specification doesn't specify any constraints on order, so I'm not sure how reliable it would be even if we made sure all of our sources were indeed ordered.

**Comment by kenfinnigan** [comment]
It's possible to get unexpected behavior if users add unordered `ConfigSource`s into their application

**Comment by dmlloyd** [comment]
Today some sources are ordered, some are sorted, and some are unordered.  So the best expectation is probably no expectation!

**Comment by davsclaus** [comment]
We did an interim workaround by some manual filtering, and ordering  and we can "kinda cope" with this on the Camel side for now.

Just mind this can bit others such as JDK 8->11 HashMap changed and they may have relied on JDK8 "ordering".

I guess its maybe harder to get something in the spec about ordering?

**Comment by dmlloyd** [comment]
It would be a subtly incompatible change in spec.  And some sources might not have a concept of "order" at all.

**Comment by kenfinnigan** [comment]
Is it something we need to consider for 2.0?

**Comment by dmlloyd** [comment]
I'm not sure there's a better solution than "don't rely on ordering".

**Comment by davsclaus** [comment]
Yeah I can see the point of sources not having ordering. 

I am talking about a properties file etc where the key=value are ordering in the file as they are in the file. and that the developer makes some assumption that because keyFoo is before keyBar then that order is what the framework will "use".

But yeah at Apache Camel we can/should likely improve our algorithm to do our own internal "reordering" so the order dont matter. We got closer with the "interim" solution we came up with a few days ago.

**Comment by dmlloyd** [comment]
Lexicographical sorting of keys could be an option.  Not the same thing but at least would yield predictability.

**Comment by radcortez** [comment]
I'm not sure if we should implement any ordering. We are not able to guarantee that user implemented ConfigSources will be ordered, plus we don't control either the backing API for System and Env.

Sorting could be an option for "predictable finite" Sources, but could pose a challenge to sort them for API's that don't provide you any way to sort at all.

I guess we could sort lexicographical for built in Sources like Env, System and file and leave the rest to the user to decide.
