### ISSUE TITLE
Converting empty string through SmallRyeConfig.convert(String, Class<T>) returns null

### ISSUE THREAD

**Issue by SergiyDyrda** [smallrye/smallrye-config#217]
Next test does not work:
```
@Test
  void fails() {
    SmallRyeConfig config = (SmallRyeConfig) ConfigProvider.getConfig();
    String converted = config.convert("", String.class);
    assertEquals("", converted);
  }
```
Previous versions of _smallrye.config_ supported this behaviour. 
Seems like `io.smallrye.config.Converters.STRING_CONVERTER` does not define _emptyValue_ for `io.smallrye.config.Converters.EmptyValueConverter`.

**Comment by dmlloyd** [comment]
That is correct. The conversion result for any empty value is always `null`.
