### ISSUE TITLE
Eclipse complains of type mismatch

### ISSUE THREAD

**Issue by emattheis** [smallrye/smallrye-config#221]
I was tinkering around with the source today and noticed Eclipse complaining about this section:

https://github.com/smallrye/smallrye-config/blob/e87d18d2e1fbc30f2faff0bdfa77f6201b4e72f8/implementation/src/main/java/io/smallrye/config/SmallRyeConfig.java#L186-L189

`Type mismatch: cannot convert from Converter<Optional<?>> to Converter<Optional<T>>`

It's all unchecked assignment anyway, so not sure why Eclipse is not compiling it. Obviously, `javac` is fine with it.

If we change the method signature to match the type of the map value then Eclipse is happy:

```java
private Converter<Optional<?>> getOptionalConverter(Class<?> asType) {
    return optionalConverters.computeIfAbsent(asType,
            clazz -> Converters.newOptionalConverter(getConverter((Class) clazz)));
}
``` 

Of course, if we do that then we need to change this section:

https://github.com/smallrye/smallrye-config/blob/e87d18d2e1fbc30f2faff0bdfa77f6201b4e72f8/implementation/src/main/java/io/smallrye/config/SmallRyeConfig.java#L130-L132

To incude an explicit cast:

```java
public <T> Optional<T> getOptionalValue(String name, Class<T> aClass) {
    return (Optional<T>) getValue(name, getOptionalConverter(aClass));
}
```

**Comment by radcortez** [comment]
Hi,

Thanks for reaching out. I'm not an Eclipse user, but I gave it a try and indeed it gives that error. I'm quite surprised, since this is a simple case.

I had a look and found a few similar issues reported in Eclipse Bugzilla:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=492939. Maybe this case needs to be reported there as well.

In my opinion, IDE's are just tools. We shouldn't change our code just to make the IDE happy. Ultimately, we must follow `javac` results. If `javac` is happy about it, then the IDE is the issue not the code.

**Comment by emattheis** [comment]
>I'm quite surprised, since this is a simple case.

Yeah, it's definitely weird. I think it's a case of `ecj` and `javac` differing on their interpretation of the JLS.

>In my opinion, IDE's are just tools. We shouldn't change our code just to make the IDE happy.

`javac` is also just a tool. It has bugs just like `ecj`, so this is not a matter of making an IDE happy, it's a matter of having an open source codebase that is as compatible with the larger Java ecosystem as possible.

>Ultimately, we must follow javac results. If javac is happy about it, then the IDE is the issue not the code.

Ultimately, the code must compile in the toolchain on the build server, but I don't see any reason not to make it work in Eclipse. Being more explicit about where unsafe type-casting takes place seems harmless.

>Maybe this case needs to be reported there as well.

It seems equally likely that `javac` could be allowing something it shouldn't. Making the code work in both places is a good hedge against running into future compiler changes that might break the build. I'm happy to file a bug with Eclipse, but I doubt we'll have a fix in hand anytime soon.

**Comment by radcortez** [comment]
@emattheis any news?

**Comment by emattheis** [comment]
@radcortez I lost track of this one. If nobody else is bothered by it, I suppose it's fine to close it.

**Comment by radcortez** [comment]
Thank you!
