### ISSUE TITLE
ZooKeeperConfigSourceTest fails with 501

### ISSUE THREAD

**Issue by radcortez** [smallrye/smallrye-config#223]
ZooKeeperConfigSourceTest is failing with 501 when resolving Maven dependencies with ShrinkWrap. This is because https is now required to access Central: https://support.sonatype.com/hc/en-us/articles/360041287334

**Comment by kenfinnigan** [comment]
We had that problem with MP OpenTracing too.

Care to fix?

**Comment by radcortez** [comment]
Sure, already on it :)

**Comment by kenfinnigan** [comment]
Thanks!

**Comment by radcortez** [comment]
Ok, this can be fixed by bumping the Arquillian Bom version, which already bumped to a fixed Maven ShrinkWrap Resolver.

The bot already bumped the dependency in the SmallRye Parent: https://github.com/radcortez/smallrye-parent/commit/24c600acaf7b5b4b13ba7b307b3b6d2510ef9c08

We just need to release it.

**Comment by kenfinnigan** [comment]
Release is done. `16` should be available in Central within the hour

**Comment by radcortez** [comment]
Cool. Thank you. I'll update the parent.
