### ISSUE TITLE
FileSystemConfigSource no longer works with ConfigMap

### ISSUE THREAD

**Issue by jmesnil** [smallrye/smallrye-config#231]
A regression was detected with smallrye-config 1.4.1 when reading properties for Kubernetes ConfigMap.

Before, [code in DirConfigSource.java](https://github.com/smallrye/smallrye-config/blob/1.3.6/implementation/src/main/java/io/smallrye/config/DirConfigSource.java) worked.
Now, [code in FileSystemConfigSource.java doesn't](https://github.com/smallrye/smallrye-config/blob/1.4.1/sources/file-system/src/main/java/io/smallrye/config/FileSystemConfigSource.java#L77).

It seems related to the change in FileSystemConfigSource that does not take into account that the ConfigMaps uses symlinks.
I've not much exception as the new code swallow the thrown exception and just got a log:

> 23:38:15,980 INFO  [org.wildfly.extension.microprofile.config.smallrye._private] (MSC service thread 1-2) WFLYCONF0003: Use directory for MicroProfile Config Source: /etc/config
> 23:38:15,993 WARN  [io.smallrye.config] (MSC service thread 1-2) Unable to read content from file /etc/config

**Comment by radcortez** [comment]
Fixed in #232.
