### ISSUE TITLE
Customer Converter<Integer> is no longer used for int types.

### ISSUE THREAD

**Issue by jmesnil** [smallrye/smallrye-config#236]
This is a regression.

In smallrye-config 1.4.1, a `Converter<Integer>` was taken into account to convert an injected `int` field.
In smallrye-config 1.6.0, this is no longer the case.

`git bisect` with the test from PR #235 identified commit a52d63b2f19eae1155434abac2911c6138c16993 as the one where regression appeared.

**Comment by dmlloyd** [comment]
Hmm it's not clear why that would be the case.  Are we not property resolving converters for primitive types?

**Comment by radcortez** [comment]
Apparently not. The converters Map has the custom converter registered for Integer but not for int (defaults to the built in one).

I'm having a look.

**Comment by dmlloyd** [comment]
Ah I see.  That's an interesting spec question: does the installed `Converter<Integer>` apply to `int.class`?  IIRC the spec says nothing about it.

**Comment by dmlloyd** [comment]
I guess the most user friendly answer should be "Yes!!".  In that case though, the `getConverter` method should map primitive types to wrapper types as the first step.

**Comment by dmlloyd** [comment]
And that would also mean there'd be no need to put the primitive types in the converter map.

**Comment by radcortez** [comment]
I've just add a look and there is no reference to that particular usage.

Anyway, apparently this was working before for Wildfly, so I think we should support it and submit a spec clarification to MP Config.

**Comment by dmlloyd** [comment]
I'll do a quick PR...

**Comment by radcortez** [comment]
I can do it as well.

**Comment by dmlloyd** [comment]
Whatever you want to do is fine.  I feel responsible for the problem though and the fix is simple.

**Comment by radcortez** [comment]
Ok, sure go ahead then. Don't be so hard on yourself :)

**Comment by radcortez** [comment]
Spec clarification in MP Config: https://github.com/eclipse/microprofile-config/pull/518
