### ISSUE TITLE
Extract Converter code to it own project

### ISSUE THREAD

**Issue by radcortez** [smallrye/smallrye-config#244]
Other MP API's or SmallRye implementations require conversions (JWT for instance). 

Maybe we could extract our conversion code to its own module first and then work on separate implementation that could be reused across all projects (and evolve into its own spec).

**Comment by kenfinnigan** [comment]
Do you mean module or SRye project?

**Comment by radcortez** [comment]
Idea was to make it in 2 steps. First as a module in SmallRye Config and then maybe as a separate SmallRye project.

**Comment by radcortez** [comment]
Idea was to make it in 2 steps. First as a module in SmallRye Config and then maybe as a separate SmallRye project.

**Comment by kenfinnigan** [comment]
Would it be better to do in one step, as then it's a one time refactor of Config to use it?

The code can still remain in Config until we have the new project ready for inclusion in Config

**Comment by radcortez** [comment]
And this was just to start the discussion about. There are some discussions in MP Config to expose the Converter API for others to use.

What I see that might make some sense is to have a separate Converter project / spec not only for consumption in other SmallRye projects, but even for App developers. You end up doing conversions between objects in one way or another.

Not sure if we want to go into that space. There are already a bunch of libraries that do Conversion.

**Comment by radcortez** [comment]
> Would it be better to do in one step, as then it's a one time refactor of Config to use it?
> 
> The code can still remain in Config until we have the new project ready for inclusion in Config

That can work.

**Comment by dmlloyd** [comment]
I think we could pilot a Converters project based on extracting our conversion code as a first step.

**Comment by kenfinnigan** [comment]
Are there open-source Converter projects that we could "re-use", or does it make the most sense to just take what we have from Config as a starting point?

Should this be moved to a smallrye-parent issue?

**Comment by dmlloyd** [comment]
:+1: - I think our converter code is a really good open source converter implementation already.

**Comment by radcortez** [comment]
Here is an initial version, just as a copy of the relevant classes to a separate repo:
https://github.com/smallrye/smallrye-converters
