### ISSUE TITLE
Eliminate new-lines from DeploymentException message when required parameters are missing

### ISSUE THREAD

**Issue by smoyer64** [smallrye/smallrye-config#27]
When the ``smallrye-config``'s ``ConfigExtension`` detects that required configuration parameters are missing, it throws a ``DeploymentException`` with a message that contains new-lines as shown below:

```shell
Error while validating Configuration
No Config Value exists for ldap.service.host
No Config Value exists for ldap.client.password
No Config Value exists for ldap.client.dn
```

This presents two problems:

1. If this message is subsequently printed out to a logging system, many static code analysis tools will flag this as a security issue.

2. If the developer wants to catch this message and provide additional information and/or formatting to the message, parsing these lines out of the message requires extra code.

I'd like to suggest that the names of the missing parameters be encapsulated in something like a ``MissingRequiredParametersException`` which can include them in a collection (encapsulated in additional structure or not) similar to the way the JavaEE components that use the _Bean Validation Framework_ reports validation problems by returning a throwing a ``ConstraintViolationException`` that encapsulates a ``Set<ConstraintViolation<T>>``.

I'd be happy to work on this if you want to assign the work to me.

**Comment by smoyer64** [comment]
Now related to:  https://github.com/eclipse/ConfigJSR/issues/87

**Comment by kenfinnigan** [comment]
We'd gladly accept a PR, thanks @smoyer64!

**Comment by smoyer64** [comment]
@kenfinnigan The Microprofile-Config specification states that a ``Converter`` that can't parse it's input ``String`` should throw an ``IllegalArgumentException``.  SmallRye wraps this exception in a ``DeploymentException`` (which I actually endorse in the issue I linked above) but when a ``Converter`` fails to parse its input the validation process stops immediately (while missing parameters are collected into the ``DeploymentException``).  Should one or both of these inconsistencies be turned into issues?

**Comment by kenfinnigan** [comment]
I think it makes sense for that yes.

Please do so and link issues where as necessary

**Comment by smoyer64** [comment]
@kenfinnigan - I've reread the CDI specifications and it's pretty specific about how the ``AfterDeploymentValidation`` event works.  It provides an ``addDeploymentProblem(Throwable)`` method that you call for each problem you encounter.  Others observing this event get to do the same.  When all observers have been serviced, if there are any deployment problems then the container is supposed to throw the ``DeploymentException``.  The specification doesn't say how the container is to indicate the problems within this ``DeploymentException``.

Weld extends ``DeploymentException`` to allow a ``List`` of causes so the RI (and presumably everyone's actual CDI implementation) does accomplish most of what I wanted - there will be a little bit of work to encapsulate the ``@ConfigProperty`` names as standalone ``Strings``.  I'll get you a PR soon!

**Comment by kenfinnigan** [comment]
No problem, thanks for investigating @smoyer64
