### ISSUE TITLE
Interceptors need to be able to intercept iteration

### ISSUE THREAD

**Issue by dmlloyd** [smallrye/smallrye-config#285]
As I stated in #196, the profile interceptor needs to be able to intercept iteration so that it can add properties found only in profiles.

Additionally, the profile interceptor needs the ability to filter out profile names, so that the set of configuration properties appears to be only the union of the set of properties present with no profile and the current profile.

It seems like a good idea to simultaneously attempt to solve the potential performance issue with iteration mentioned on the MP Config project.  The issue is that it is sometimes the case that iteration of config properties intends to get the value as well as the key, because lookup of individual keys might be somewhat slower than iterating the full key-value entries of the configuration for some configuration sources.  So it might be a good idea to have two iteration mechanisms: one for names (String) and one for name+value (ConfigValue).

**Comment by radcortez** [comment]
If we are thinking in unifying ConfigSource and Interceptors and even intercept the iteration, do you think that `ConfigSource` should be exposed in the Interceptor chain? Like `proceed(ConfigSource, String)?

**Comment by dmlloyd** [comment]
We don't really know what config source (if any) would service the request.  I think that it might be useful to look at it the opposite way: represent a config source *as* an interceptor, since they're fundamentally similar in the end (including being arranged by priority).  It might even be useful to interleave "traditional" interceptors with config sources, so that some interceptors might (for example) only intercept values from some configuration sources.

We don't want to leak the config source at any rate IMO.

**Comment by radcortez** [comment]
So, for instance right now, we could replace our last interceptor in the chain by a N interceptors where N is the number of Config Sources and each interceptor added in the end is a wrapper around the ConfigSource `getValue`. This would give us the same behaviour and prepare for the next step.

We then need to revise the priorities on both ConfigSources and Interceptors. We probably still want for the majority of the interceptors to run ahead of the ConfigSources.

I'm now wondering if we should take a step back and maybe add this behaviour to the `ConfigValueSource` and drop the interceptor API by adding some methods that receive the `ConfigValue` returned by previous ConfigSources. So, in the end is a combination of the current `ConfigSource` and the Interceptor API but in a single API, so you don't need to know which one to use or implement, there is only one.

**Comment by dmlloyd** [comment]
I think this is a reasonable step forward.  But there could still be value in retaining a "config source" concept where simple config sources do not need to understand the possibility of having a "proceed" step.  It could be an interceptor under the covers but delegating to the simpler API.

**Comment by radcortez** [comment]
Or maybe even support implementations so they can implement both `ConfigValueSource` and `ConfigSourceInterceptor` in the same class. Or add a `ConfigurableSource` that extends from `ConfigValueSource` and adds the interceptors methods.

**Comment by radcortez** [comment]
Well, I'm work on a PR to just change the implementation for now and see how that goes.

**Comment by radcortez** [comment]
@dmlloyd I'm looking into this and we may need to make a few decisions:

To apply interceptors in the iterations and I assume we are for now referring to `getPropertyNames`, we don't want the final interceptor or ConfigSource wrapping interceptors to call `getValue`, since we don't need it and it may be an expensive operation.

We either have to keep two chains (one with ConfigSource to call with getValue, and another one without that just calls the interceptor without value, so we can apply the Profile changes). Or, we need to introduce some sort of mechanism, maybe in `ConfigSourceInterceptorContext` so we can selectively run or skip chain calls, depending on what we want to do.

Any thoughts? Or did I missed what you wanted to do?

**Comment by dmlloyd** [comment]
I think you misunderstood, or I didn't explain clearly.

We know interceptors which transform names or values also must be allowed to change the apparent set of configuration names that are available.  We know that users have requested the ability to iterate values because iterating names and doing a lookup on each name may be expensive.

So I would conclude that we need perhaps two new methods on the interceptor API (and correspondingly on the interceptor context:

```java
// this is simplified pseudocode
default Iterator<String> iterateNames(InterceptorContext ctxt) { return ctxt.iterateNames(); }
default Iterator<ConfigValue> iterateValues(InterceptorContext ctxt) { return ctxt.iterateValues(); }
```

This allows any interceptor to either iterate or get values from either the getValue or iterate* methods.  The profile interceptor will be able to return iterators that transforms names and/or drops values as needed.

It might be that having a separate name iteration method is pointless - because some interceptors might need to iterate values in order to get the correct set of names.  But I think that's something that should be analyzed further before drawing a conclusion.

**Comment by radcortez** [comment]
I think I've got it. I was not sure if we wanted to add something new to the interceptor, so I've actually implemented it with the current API and apply interceptors in `Config.getPropertyNames` :)

Since we are open to add specific methods, I'll change it.

**Comment by radcortez** [comment]
@dmlloyd Here is a draft for the work: https://github.com/smallrye/smallrye-config/pull/287. Please, let me know what you think about the direction. Thanks!
