### ISSUE TITLE
Wrong docu on interceptors

### ISSUE THREAD

**Issue by svenhaag** [smallrye/smallrye-config#314]
Hi, I think there is a bug in the interceptors documentation at:
https://github.com/smallrye/smallrye-config/blob/1.8.0/doc/modules/ROOT/pages/interceptors/interceptors.adoc#built-in-interceptors

It says:
> None of the interceptors is registered by default.

But the default Config adds all the awesome new stuff. See:
`io.smallrye.config.SmallRyeConfigFactory.Default`.
```
configProviderResolver.getBuilder().forClassLoader(classLoader)
                    .addDefaultSources()
                    .addDefaultInterceptors()
                    .addDiscoveredSources()
                    .addDiscoveredConverters()
                    .addDiscoveredInterceptors()
                    .build();
```

**Comment by radcortez** [comment]
Thanks! I guess I forgot to change it. I'll fix it.
