### ISSUE TITLE
Allow activation of multiple configuration profiles

### ISSUE THREAD

**Issue by famod** [smallrye/smallrye-config#363]
As discussed [over at Quarkus](https://github.com/quarkusio/quarkus/issues/9895), 
I and others would really like to enable multiple profiles to be able to apply a DRY and KISS configuration approach.

So I'd like to follow @radcortez' invitation:
> BTW if you want to support this OOTB, please open an issue in SmallRye Config :)

🙂

**Comment by radcortez** [comment]
I'll see what I can do :)

**Comment by famod** [comment]
Awesome!
I must admit that I did not check the mp-config spec but I suppose this topic is a blind spot there?

**Comment by radcortez** [comment]
Yes it yes. Only now in MP 2.0 (not released yet) are profile aware configurations being added.

**Comment by famod** [comment]
@radcortez any news on this one? Thanks!

**Comment by radcortez** [comment]
Not yet, since we were mostly focusing on 1.9 and 2.0. With 1.9 released and 2.0 complete we can probably find some time to work on this now.

**Comment by Emily-Jiang** [comment]
I guess we are talking about different types of profile, such as one for stage, and the other for database. I don't think you want to turn on the profile for both `test` and `prod`. I think Spring uses profile to turn on database and project stage. If my assumpation is correct, I think it is good to proceed. Otherwise, I think it will cause a big mess.

**Comment by radcortez** [comment]
In the API and in the implementation we don't really have any special meaning or reserved profiles names. Profiles are just profiles. 

In Quarkus, yes we do have semantic meaning for particular profiles. Anyway, this does not stop you to support multiple profiles. We had that request here https://github.com/quarkusio/quarkus/issues/9895.

From a spec perspective, it may be limiting to say that only one profile may be active at a time and maybe the spec should open up a bit to allow such cases for implementors. Anyway, this is only supported for our own profile property, so we are not contradicting the spec.

**Comment by Emily-Jiang** [comment]
Since we have not released MP Config spec as yet, maybe we should relax the spec to allow implementation to support multiple config profiles since Spring supports this [feature](https://www.baeldung.com/spring-profiles).

**Comment by radcortez** [comment]
> Since we have not released MP Config spec as yet, maybe we should relax the spec now to allow implementation to support multiple config profiles since Spring supports this [feature](https://www.baeldung.com/spring-profiles).

Ok, I'll send a PR with a proposal.
