### ISSUE TITLE
No Config Value exists for required property excption in case of empty String

### ISSUE THREAD

**Issue by rsoika** [smallrye/smallrye-config#393]
After upgrading from Wildfly 18 to Wildfly 20 I run into a problem concerning Injecting optional config values.
I saw that there was a discussion some time ago in issue #334 

I think the current implementation (included in Wildfly 20) is not correct. I have the following lines of code in one of my libraries:

```
	@Inject
	@ConfigProperty(name = "setup.system.model", defaultValue = "")
	String setupSystemModel;
```

The configuration param "setupSystemModel" is from the perspective of my business logic optional.
Later in my code I verify if a SetupSystemModel was provided by the deplyment: 

```
   if (!setupSystemModel.isEmpty()) {
     ... do something ...
   }
```

Now with the new implementation this is no longer working because I run into the deployment exception 

`"No Config Value exists for required property " + key)`

and can't deploy my application any more. 
In the microprofile 2.0 [docs](https://download.eclipse.org/microprofile/microprofile-2.0-javadocs-test/apidocs/org/eclipse/microprofile/config/inject/ConfigProperty.html) I found this : 

> Injecting Optional Values
> Contrary to natively injecting, if the property is not specified, this will not lead to a DeploymentException. The following code injects a Long value to the my.optional.long.property. If the property does not exist, the value 123 will be assigned. to injectedLongValue.
> 
>  @Inject
>  @ConfigProperty(name="my.optional.long.property", defaultValue="123")
>  private Long injectedLongValue;
 

Even if this example is not very clear I do not think that the following code should throw a deplyoment excption:
 
 @ConfigProperty(name="my.optional.long.property", defaultValue="")

As a result of the implementation (provided in wildfly 20) now I am forced to implement a very ugly piece of code like this one:

```
	@Inject
	@ConfigProperty(name = "setup.system.model", defaultValue = "NONE")
	String setupSystemModel;
...
.......
   if (!setupSystemModel.isEmpty() && !"NONE".equals(setupSystemModel)) {
     ... do something ...
   }
```

What do you think? Is there any open discussion about providing empty strings as default values which I missed?

**Comment by radcortez** [comment]
Hi @rsoika,

There has been some discussion around how to represent empty values / empty strings. You can find the discussion here: https://github.com/eclipse/microprofile-config/issues/446

For some time, in SR Config, we already implement this:
https://github.com/smallrye/smallrye-config/issues/211

The point is that using an empty String, will effective prevent you to empty the configuration value in a higher ordinal ConfigSource. 

For your particular case, I recommend to use `Optional`.

**Comment by rsoika** [comment]
Thanks for your response. Can you give me a short example how to use Optional? I can't find an example how this can be used.

**Comment by radcortez** [comment]
Just use:

```java
@Inject
@ConfigProperty(name = "setup.system.model")
Optional<String> setupSystemModel;
```

Then you just use the `Optional` API to check if the value is present: `java.util.Optional#isPresent`.

**Comment by radcortez** [comment]
It there is nothing else to be clarified here, I'll be closing this issue. Feel free to reopen if you need anything else.
