### ISSUE TITLE
Certain validation failures cause further injection points not to be checked

### ISSUE THREAD

**Issue by Azquelt** [smallrye/smallrye-config#409]
In `ConfigExtension.validate`, there is clearly an attempt to detect all validation issues and add each of them as a deployment problem.

However, there are cases which will cause the validate method to throw an exception or return, meaning that it won't validate further injection points.

In particular:
* [Line 140 can `return`](https://github.com/smallrye/smallrye-config/blob/mpconfig20/implementation/src/main/java/io/smallrye/config/inject/ConfigExtension.java#L140)
* [Line 144, `getPropertyKey()` can throw an exception](https://github.com/smallrye/smallrye-config/blob/mpconfig20/implementation/src/main/java/io/smallrye/config/inject/ConfigExtension.java#L144)

(line numbers based on the `mpconfig20` branch)

**Comment by radcortez** [comment]
https://github.com/smallrye/smallrye-config/pull/412/ Should fix this.

On `io.smallrye.config.inject.ConfigProducerUtil#getConfigKey`, I believe it should be fine. Did you have any trouble with it?

**Comment by Azquelt** [comment]
`io.smallrye.config.inject.ConfigProducerUtil#getConfigKey` will throw an exception if the `name` isn't set for the `ConfigProperty` annotation and it can't work out a default name (e.g. because the injection point is a method parameter and the parameter name is not available).

However, `ConfigExtension.validate` won't catch this exception and therefore won't validate any further injection points.

**Comment by radcortez** [comment]
Ah, right! Forgot about the method parameter injection. I'll fix it. Thank you!

**Comment by radcortez** [comment]
Actually, it should be fine. Any exception thrown in the `AfterDeploymentValidation` observer event is added as a deployment problem.

**Comment by radcortez** [comment]
Here is the test: https://github.com/smallrye/smallrye-config/blob/master/implementation/src/test/java/io/smallrye/config/inject/ValidateInjectionTest.java#L62-L72

**Comment by Azquelt** [comment]
This is true, and the error will be reported, but no further validation will be done. I think it would be preferable if we could report all the validation issues, rather than stopping if we hit this one. I'll make a PR for this.

**Comment by radcortez** [comment]
Sure.
