### ISSUE TITLE
Injecting an undefined Config Property value with an Optional Converter returns the wrong value

### ISSUE THREAD

**Issue by Joseph-Cass** [smallrye/smallrye-config#413]
For the following ConfigProperty Injection:
``` 
@Inject
@ConfigProperty(name = "unknown") // where unknown is not defined anywhere
Optional<MyStringObject> unknownOptional; // where MyStringObject is a simple class with a get and set method for a String
```

Which has the following Converter:
```
public class MyStringObjectConverter implements Converter<MyStringObject> {

    @Override
    public MyStringObject convert(String value) {
        MyStringObject obj = new MyStringObject();
        obj.setValue(value);
        return obj;
    }

}
```

The SmallRye implementation returns the following unknownOptional:
```
unknownOptional.isPresent() -> true
unknownOptional.get().getValue() -> ""
```

According to the MP Config specification, I think this should be:
```
unknownOptional.isPresent() -> false
unknownOptional.get().getValue() -> Exception
```

**Comment by Joseph-Cass** [comment]
Similarly, 
```
    @Inject
    @ConfigProperty(name = "unknown") // where unknown is not defined anywhere
    MyStringObject unknownOptional;
```

Does not throw any Exception, when I think it should.

**Comment by dmlloyd** [comment]
You are correct about the specification from the perspective of the injected value.  However, if a converter detects an empty value (in your case, an empty string), it must return `null`.  If you add this check to `MyStringObjectConverter`, you should get the expected result.

**Comment by Joseph-Cass** [comment]
Thanks for the quick response @dmlloyd. I presume you're refering to [this part](https://github.com/eclipse/microprofile-config/blob/2c42cc9f86112aef975ee5e06e90aef1dd6379df/api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java#L147) of the spec?

Adding `if (value == "") return null;` to the converter leads to the following behaviours:


1. ```
   @Inject
   @ConfigProperty(name = "unknown")
   Optional<MyStringObject> unknownOptional;
   ```
   unknownOptional.get().getValue() -> ""

2. ```
   @Inject
   @ConfigProperty(name = "unknown")
   MyStringObject unknownOptional;
   ```
   unknownOptional.getValue() -> org.eclipse.microprofile.config.configproperty.unconfigureddvalue

Is this what you expected?

**Comment by dmlloyd** [comment]
It would not be what I expected at all, no.  @radcortez wdyt?

**Comment by radcortez** [comment]
Hum, if `MyStringObject` Converter returns `null`, then the `Optional` should be empty. I'll check if there is some kind of issue with this.

**Comment by radcortez** [comment]
It this the use case @Joseph-Cass ? https://github.com/smallrye/smallrye-config/commit/47ffb8e626d9c5122cab4c4fe46c0b85b28d2052

**Comment by Joseph-Cass** [comment]
Yes, as long as the Config Property name "converted" is not defined anywhere outside of those files, I believe that's the same. Thanks @radcortez .

Did you try running those new tests @radcortez ?

**Comment by Joseph-Cass** [comment]
Oh wait sorry, shouldn't
```
@ConfigProperty(name = "converted")
private ConvertedValue convertedValue;
``` 
throw a deployment exception according to [this bit of spec](https://github.com/eclipse/microprofile-config/blob/1280fb092be8bdd5ee61233cefef3ad326de923b/api/src/main/java/org/eclipse/microprofile/config/inject/ConfigProperty.java#L60)?

**Comment by radcortez** [comment]
> Yes, as long as the Config Property name "converted" is not defined anywhere outside of those files, I believe that's the same. Thanks @radcortez .
> 
> Did you try running those new tests?

Yes. Here is the build: https://github.com/smallrye/smallrye-config/actions/runs/292083519

**Comment by Joseph-Cass** [comment]
> Thanks for the quick response @dmlloyd. I presume you're refering to [this part](https://github.com/eclipse/microprofile-config/blob/2c42cc9f86112aef975ee5e06e90aef1dd6379df/api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java#L147) of the spec?
> 
> Adding `if (value == "") return null;` to the converter leads to the following behaviours:
> 
> 1. ```
>    @Inject
>    @ConfigProperty(name = "unknown")
>    Optional<MyStringObject> unknownOptional;
>    ```
>    
>    
>    unknownOptional.get().getValue() -> ""
> 2. ```
>    @Inject
>    @ConfigProperty(name = "unknown")
>    MyStringObject unknownOptional;
>    ```
>    
>    
>    unknownOptional.getValue() -> org.eclipse.microprofile.config.configproperty.unconfigureddvalue
> 
> Is this what you expected?

I think I may have had made a mistake when I was running these tests... sorry... I'm now getting different results:
1. ```
   @Inject
   @ConfigProperty(name = "unknown")
   Optional<MyStringObject> unknownOptional;
   ```
   unknownOptional.get().getValue() -> false

2. ```
   @Inject
   @ConfigProperty(name = "unknown")
   MyStringObject unknownOptional;
   ```
   unknownOptional.getValue() -> org.eclipse.microprofile.config.configproperty.unconfigureddvalue

However, the latter still seems to contradict the new `converters()` test you've made @radcortez ? I'd have thought the Converter should return `null` rather than `"out"`?

**Comment by radcortez** [comment]
> However, the latter still seems to contradict the new `converters()` test you've made @radcortez ? I'd have thought the Converter should return `null` rather than `"out"`?

Yes, I've implemented the `Converter` to always return `out` if the value is empty or `null`. If you return `null` from the `Converter` if any value, then the injection is also `null`.

**Comment by radcortez** [comment]
Ah, nvm, I see what you mean now. There is an issue with validation that I've fixed here: https://github.com/smallrye/smallrye-config/pull/412

**Comment by radcortez** [comment]
I've merged #412. Let me know if it is better.

**Comment by Joseph-Cass** [comment]
With the latest version of the code, I'm now getting `org.jboss.weld.exceptions.DeploymentException: SRCFG02000: No Config Value exists for required property unknown` for:
```
@Inject
@ConfigProperty(name = "unknown")
MyStringObject unknownOptional;
```
Which I think is correct.

I've also just noticed the following test got removed: https://github.com/smallrye/smallrye-config/blob/47ffb8e626d9c5122cab4c4fe46c0b85b28d2052/implementation/src/test/java/io/smallrye/config/inject/ConfigInjectionTest.java#L69 do you agree the Injection of `convertedValue` should have thrown a `DeploymentException`?

**Comment by radcortez** [comment]
Yes!

**Comment by Joseph-Cass** [comment]
Great. Happy to close this issue. Thanks :)

**Comment by radcortez** [comment]
Thanks!
