### ISSUE TITLE
Setting `config_ordinal` property in META-INF/microprofile-config.properties should change the ordinal of the PropertiesConfigSource

### ISSUE THREAD

**Issue by NicoNes** [smallrye/smallrye-config#417]
Hi @Joseph-Cass  and @radcortez,

The fix for issue https://github.com/smallrye/smallrye-config/issues/401 does not completely close this issue https://github.com/eclipse/microprofile-config/issues/573.

Actually setting 'config_ordinal' in `META-INF/microprofile-config.properties` file still does not override the `PropertiesConfigSource` object ordinal.

**Comment by radcortez** [comment]
Hi @NicoNes, can you provide more details?

I've added a test here: https://github.com/smallrye/smallrye-config/pull/421

And it seems to be working.

**Comment by NicoNes** [comment]
Hey @radcortez ,

You are right things works pefectly well, the problem was actually in my test case. Sorry for that.

**Comment by radcortez** [comment]
Great! Let me know if you need anything else :)
