### ISSUE TITLE
Builtin converters must throw NPE if asked to convert null

### ISSUE THREAD

**Issue by Azquelt** [smallrye/smallrye-config#422]
eclipse/microprofile-config#542 clarified that it's invalid to pass `null` to a converter and added a requirement that all built in converters must throw a `NullPointerException` if this occurs.

Currently smallrye-config doesn't do this because the `TrimmingConverter` will return `null` if passed `null`.

I'm happy to make a PR to fix this, but I'm not sure if it should be against `master` or `mpconfig20` - both branches have the issue, but the requirement was only added to the spec in 2.0.

Note the test for this was broken in the TCK and wasn't running but has been fixed by eclipse/microprofile-config#628

**Comment by radcortez** [comment]
Hi @Azquelt, thanks!

I've noticed this when I was validated eclipse/microprofile-config#628 and added a fix: https://github.com/smallrye/smallrye-config/commit/fcd1c0245977997aee9535001c009b3f50dcfee7

Since the requirement is only for 2.0, I've only added it to the `mpconfig20` branch.
