### ISSUE TITLE
Creating exceptions via MessageBundle interface is slower

### ISSUE THREAD

**Issue by Azquelt** [smallrye/smallrye-config#428]
The Liberty performance team flagged up a slowdown in when exceptions are created via the `ConfigMessages` interface. We had a component using `getValue` to lookup config properties that didn't exist and then handling the thrown exception. The performance team let us know that **>90%** of the time spent in the `getValue()` call was spent within `ConfigMessages.propertyNotFound`, and specifically in `Throwable.getStackTrace()`.

In this case, we told them to change to use `getOptionalValue` if the property may not exist, but I did wonder if this is a common mistake which may hit users.

Experimenting locally, I found that the problem is worse on OpenJ9 than on hotspot. Comparing the time taken for 200k calls to `getOptionalValue` vs. `getValue` in a try-catch:
* Hotspot: x40
* OpenJ9: x80

I tried changing `ConfigMessages.propertyNotFound` to return a `String` rather than an exception and creating the exception in `SmallRyeConfig`. This gave the following results (again for `getOptionalValue` vs `getValue` in a try-catch):
* Hotspot: x8.7
* OpenJ9: x3.35

(both sets of tests done on jdk-15+36 from adoptopenjdk)

Caveats:
* These tests aren't terribly scientific, and it would be good to know if someone else sees a similar performance penalty for exceptions created via a `@MessageBundle` interface
* This was only a problem because of a user error. They shouldn't have been throwing and catching exceptions on a non-exceptional code path.

**Comment by radcortez** [comment]
Hum,

Probably related to this?

```java
    private static void _copyStackTraceMinusOne(final Throwable e) {
        final StackTraceElement[] st = e.getStackTrace();
        e.setStackTrace(Arrays.copyOfRange(st, 1, st.length));
    }
```

Can you confirm?

**Comment by Azquelt** [comment]
Yeah, `propertyNotFound` -> `_copyStackTraceMinusOne` -> `getStackTrace` was the stack, with the time being spent inside `getStackTrace`.

I did have a look and it seemed like that code had been in jboss logging for years, so it doesn't look like a new issue.

**Comment by radcortez** [comment]
This code is generated.

@dmlloyd any thoughts?

**Comment by dmlloyd** [comment]
It's not an issue because this is "exceptional" code.  The bug here is whatever is using `getValue` rather than `getOptionalValue` for an optional value: normally if a value is not found (at least in the generated code) we should be exiting after one exception is thrown.

**Comment by Azquelt** [comment]
That's fair enough, I only raised it because I was surprised at how much slower it was than a regular exception, particularly on OpenJ9.

**Comment by Emily-Jiang** [comment]
I came acorss this problem and disagreed with doing nothing for this issue. It is a legimitate use case here. A developer expects the property `my.mandatory.prop` exists, he then calls `config.getValue()`. According to the spec, it is correct to be displayed with an exception so that he can fix it. However, the performance is really unacceptable. I am confused why should this issue be closed without being fixed? Any thoughts @radcortez ?

**Comment by Emily-Jiang** [comment]
How about not dumping the whole stack `e.setStackTrace(Arrays.copyOfRange(st, 1, st.length));`?

**Comment by dmlloyd** [comment]
This would be an issue to raise here: https://issues.redhat.com/browse/JBLOGGING

**Comment by hutchig** [comment]
There are actually 3 (or 2.9 :-) ) array copies of the stack here:

1. e.getStackTrace() always copies the stack as ["Writes to the returned array do not affect future calls to this method."](https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html#getStackTrace()),
2. then the coded copyOfRange to loose the top method, 
3. the e.setStackTrace() will then also copy the array as ["Writes to the returned array do not affect future calls to this method."](https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html#setStackTrace(java.lang.StackTraceElement[]))

The error path of the spec implementation and the error path of an application are distinct
but either of them being active will, netted out, take the codepath out of the 'normal' working set.

I wonder what harm would be done by leaving the synthetic method (or whatever noise it is) there as the top frame
versus what is really gained by any performance improvement?

**Comment by dmlloyd** [comment]
➡️ https://issues.redhat.com/browse/JBLOGGING 😉

**Comment by Emily-Jiang** [comment]
@dmlloyd https://issues.redhat.com/browse/JBLOGGING-148

**Comment by Emily-Jiang** [comment]
In light of the conversation on https://issues.redhat.com/browse/JBLOGGING-148, @Azquelt can you reopen this issue to explore the comments made by James Perkins.

> The reason for this is to remove the interface method from the stack trace. If an exception is thrown that frequently I would probably suggest using a string rather than returning an exception. Other than that I'm not too sure what could be done short of adding a build parameter which would not set the stack trace. However that means the implementation method would end up in the stack trace.
