### ISSUE TITLE
Should EnvConfigSource cache results which are not found?

### ISSUE THREAD

**Issue by Azquelt** [smallrye/smallrye-config#440]
I saw that #396 added a cache for entries in the env config source to avoid doing the character replacement on the key on every lookup and to align with Quarkus.

However, I note that it doesn't add anything to the cache if the key is not found in the config source, meaning that repeated lookups for the same key which isn't present anywhere will result in the character replacement on the key being repeated on every lookup. This happens relatively frequently because other microprofile specs allow the user to change the default behaviour by setting config properties and so implementations must check to see if they're set.

Our performance testing picked this up as being slower than other config sources and I notice that [EnvConfigSource][env-config-source] in Quarkus does cache missing values using a `NULL_SENTINAL`.

Is there a reason that missing values are not cached in the smallrye-config `EnvConfigSource`?

[env-config-source]:https://github.com/quarkusio/quarkus/blob/master/core/runtime/src/main/java/io/quarkus/runtime/configuration/ConfigUtils.java#L126

**Comment by radcortez** [comment]
No reason at all. I've probably forgot. I'll add it.
