### ISSUE TITLE
Backslashes are removed from property values

### ISSUE THREAD

**Issue by Azquelt** [smallrye/smallrye-config#450]
When a config property contains backslashes, they get treated specially:
* Some sequences like `\n`, `\t`, `\b` get converted to special characters
* Otherwise the backslash is just removed

I can't see anything in the spec which would require this behaviour.

This particularly causes problems if the user tries to put a windows file path in a config property.

**Comment by Azquelt** [comment]
@radcortez I think you've fixed this by disabling `ESCAPES` in 468aaf1d?

**Comment by radcortez** [comment]
Yes.

I'm sorry, I didn't put any feedback here because I was still trying it out with Quarkus.

Did that fix the issue on your end?

**Comment by Azquelt** [comment]
I still need to test it but removing `ESCAPES` was the change that I was going to try, so I'm hopeful :)

**Comment by Azquelt** [comment]
Yes, this works for me.
