### ISSUE TITLE
ConfigProperties camelCase bug

### ISSUE THREAD

**Issue by Joseph-Cass** [smallrye/smallrye-config#476]
Defining a Config Property with a camelCase key in a `ConfigProperties` class leads to checks for an incorrect Config Property, throwing a `java.util.NoSuchElementException:` 

For example, defining a ConfigPropertiesPOJO:
```
@ConfigProperties(prefix = "myPrefix")
@Dependent
public class ConfigPropertiesPOJO {
    public String stringKey;
}
```

With the following in a Config Source:
```
myPrefix.stringKey=validValue
```

Leads to checks for `myPrefix.string-key` which throws `java.util.NoSuchElementException: SRCFG00014: Property myPrefix.string-key not found`.

**Comment by Emily-Jiang** [comment]
It seems [this](https://github.com/smallrye/smallrye-config/blob/mpconfig20/implementation/src/main/java/io/smallrye/config/ConfigMappingProvider.java#L124) logic added the - and convert upper case to lower case. @radcortez this configkey `stringKey` is a valid name though.

**Comment by radcortez** [comment]
We follow a different naming strategy for Quarkus, so we can't just change that piece. I've added an initial work to support NamingStrategies.
