### ISSUE TITLE
More detailed Error messages

### ISSUE THREAD

**Issue by Joseph-Cass** [smallrye/smallrye-config#485]
Could we include some more detailed logging messages to help users debug exceptions? Particularly for `Exception`s caused by `@Injection`s, and also MicroProfile Config 2.0 specific features.

For example, Injecting a `@ConfigProperties` bean where invalidPrefix.akey doesn't exist, e.g.:
```
@Inject
@ConfigProperties(prefix = "invaldPrefix")
ConfigPropertiesPOJO details;
```
Leads to: `NoSuchElementException: SRCFG00014: Property invaldPrefix.akey is required but the value was not found or is empty`

Could this include `@ConfigProperties` specific information? e.g. `No Config Property exists for the prefix <prefix name> for the field <field name>`

Also, I think we should ensure any MicroProfile Config key terms are used and capitalised where appropriate, e.g. the following could be `Required Config Property %s not found`:
https://github.com/smallrye/smallrye-config/blob/bb3d4ab40c720a34b11b6112dabf56690137fe1d/cdi/src/main/java/io/smallrye/config/inject/InjectionMessages.java#L34

**Comment by Joseph-Cass** [comment]
I also think all the following should say which `Config Property` caused the `Exception`:
https://github.com/smallrye/smallrye-config/blob/bb3d4ab40c720a34b11b6112dabf56690137fe1d/implementation/src/main/java/io/smallrye/config/ConfigMessages.java#L105-L115

**Comment by radcortez** [comment]
Sure. Can you one a PR with a proposal?

**Comment by Joseph-Cass** [comment]
This is still on my todo list, but it keep getting pushed down :( 

I'd like to go through all the messages thoroughly rather than just change the ones I've highlighted

**Comment by Joseph-Cass** [comment]
Another potential logging message improvement has been highlighted:
```
@Inject
    @ConfigProperty(name = "some.properties", defaultValue = "")
    private List<String> someProps;
```
Returns an error that some.properties wasn't set, which is somewhat confusing because a defaultValue was "set". We should probably try to improve that error message to state that empty strings are treated as missing values.

**Comment by radcortez** [comment]
No worries, take your time :)

**Comment by Joseph-Cass** [comment]
@radcortez What do you think about the idea of utilising the new [ConfigValue](https://download.eclipse.org/microprofile/microprofile-config-2.0/apidocs/org/eclipse/microprofile/config/ConfigValue.html) class to "upgrade" any [ConfigMessages](https://github.com/smallrye/smallrye-config/blob/master/implementation/src/main/java/io/smallrye/config/ConfigMessages.java) which are related to ConfigProperty's?

For example, 
```
@Message(id = 11, value = "Could not expand value %s in property %s")
NoSuchElementException expandingElementNotFound(String key, String valueName);
```

Could be changed to:
```
@Message(id = 11, value = "Could not expand value %s in the config property: %s")
NoSuchElementException expandingElementNotFound(String key, String configPropertyDetails);
```
Where `configPropertyDetails` is generated from a new `ConfigValue.toString()` method to output a final message such as:
```
SRCFG00011: Could not expand value my.prop in the config property:
Config property name: expression
Config property value: "${my.prop}"
Config source name: KeyValuesConfigSource
Config source ordinal: 100
```
Example from: https://github.com/smallrye/smallrye-config/blob/f4489d8a873ea633925a35f583f2892b04c19898/implementation/src/test/java/io/smallrye/config/ExpressionConfigSourceInterceptorTest.java#L67-L74

**Comment by radcortez** [comment]
Sounds good, but I think we should not rely on `toString` with line breaks. This may break logger parsers and not correctly associate all the information to a single log line.

We can either pass the additional elements to the log line, or just build it and pass it all together. What do you think?

**Comment by Joseph-Cass** [comment]
Okay that's fair enough. I wasn't convinced by the line breaks anyway. 

I guess there's some pros and cons between the two alternatives you've proposed:

1. Pass the additional elements to the log line
    - More freedom with formatting
    - Need to think clearly about exactly what information the user may want for each logging message
e.g.
```
@Message(id = 11, value = "Could not expand value %s in property %s from the config source %s(ordinal=%s)")
NoSuchElementException expandingElementNotFound(String key, String valueName, String configSource, String configOrdinal);
```

2. Pass a ConfigValue.toString()
    - More standardisation across logging messages
    - Can only be applied to messages which have access to ConfigValue 
e.g.
```
@Message(id = 11, value = "Could not expand value %s in the property: %s")
NoSuchElementException expandingElementNotFound(String key, String configValueToString);
```

I think I like 2. But I could be persuaded :)

**Comment by radcortez** [comment]
Maybe 1 should be better. Not only we don't have access to the `ConfigValue` object all the time, but also we may not have some fields available in the `ConfigValue` itself.

**Comment by Joseph-Cass** [comment]
Okay, sounds good. I'll look through the existing logging messages and see where we could utilise the new ConfigValue object. 

For general "rule-of-thumb"s for logging messages do you think the following sound okay?
- Wrapping all config values in quotes such as: `\"%s\")` e.g. `"my.config.value"` (currently, some do and some don't)
- Where adding config source information is appropriate, format the output as: `%s(ordinal=%s)`, e.g. `KeyValuesConfigSource(ordinal=100)`
- Adding `@Cause`s for appropriate [InjectionMessages](https://github.com/smallrye/smallrye-config/blob/master/cdi/src/main/java/io/smallrye/config/inject/InjectionMessages.java)
- I know this contradicts what I said in the original issue, but refer to config key values as they appear in the spec. e.g `property -> config property` (and not `Config Property` as I originally suggested)

**Comment by Joseph-Cass** [comment]
@radcortez what is the purpose of [ConfigException.java](https://github.com/smallrye/smallrye-config/blob/97e855b4bb6bad2e8ac45256490d04c44a4747b4/cdi/src/main/java/io/smallrye/config/inject/ConfigException.java#L25)? And is there a reason why it's only used in 2 Injection Exception messages?
https://github.com/smallrye/smallrye-config/blob/97e855b4bb6bad2e8ac45256490d04c44a4747b4/cdi/src/main/java/io/smallrye/config/inject/InjectionMessages.java#L20-L26

**Comment by radcortez** [comment]
It seems it was added here: https://github.com/smallrye/smallrye-config/pull/28

Feel free to use it in other places, or if you feel it can be removed I'm also fine with it. Thanks!

**Comment by Joseph-Cass** [comment]
Okay, thanks! I like the idea of "wrapping" all Config CDI Injection Exceptions in a common Exception class, like  `ConfigException` (but perhaps renamed to ` ConfigInjectionException`?) and throwing them with a `@Cause Exception e`?

Then for n different DeploymentException's we could (theoretically) get:
```
org.jboss.weld.exceptions.DeploymentException: Exception List with n exceptions:

Exception 0 : 
io.smallrye.config.inject.ConfigInjectionException: SRCFG0200X: < a SmallRye InjectMessages>
...
caused by:
the.root.cause.Exception: SRCFG0000X: < a SmallRye ConfigMessages>
 
 ... 

Exception n : 
io.smallrye.config.inject.ConfigInjectionException: SRCFG0200X: < a SmallRye InjectMessages>
...
caused by: 
the.root.cause.Exception: SRCFG0000X: < a SmallRye ConfigMessages>
```

What do you think?

**Comment by radcortez** [comment]
I'm ok with that. Please feel free to propose a change :)

**Comment by Joseph-Cass** [comment]
Perhaps the `Exception` should be appended to the end of this String:
https://github.com/smallrye/smallrye-config/blob/7324f303832f08f41d5a1cbf2772eb7db41d4fc2/implementation/src/main/java/io/smallrye/config/ConfigMessages.java#L136-L137
