### ISSUE TITLE
Certain Exceptions block other Exceptions being logged

### ISSUE THREAD

**Issue by Joseph-Cass** [smallrye/smallrye-config#486]
Similarly to https://github.com/smallrye/smallrye-config/issues/409, when certain `Exceptions` occur, they can block other `Exceptions` being returned to the user.

In particular, I'm seeing a Property Expression Exception, `SRCFG00011`, blocking some messages from other invalid `@ConfigProperty` Injections.

**Comment by Joseph-Cass** [comment]
I'm looking into this now

**Comment by radcortez** [comment]
OK, let me know.

**Comment by Joseph-Cass** [comment]
@radcortez Some other things have come up so I don't think I'll be able to have a look at this for a day or two at least. I'm still happy to look at it though.

**Comment by radcortez** [comment]
We are not in a rush, so take your time :)
