### ISSUE TITLE
Question: Any reference for how to write and register a custom Config source?

### ISSUE THREAD

**Issue by dzou** [smallrye/smallrye-config#491]
Hello,

I'm interested in writing a custom config source which retrieves values from a secrets store.

I'm planning on following the examples [found here](https://smallrye.io/docs/smallrye-config/config-sources/config-sources.html#configvalueproperties-config-source). One question I had was about how to register custom config source to your Quarkus app; I saw for the [config value source](https://smallrye.io/docs/smallrye-config/config-sources/config-sources.html#configvalueproperties-config-source):

> This Config Source is not automatically registered. This means that need to provide your own ConfigSourceProvider implementation and registration via ServiceLoader to use this Config Source like documented in MicroProfile Config ConfigSource specification.

I was wondering if someone could clarify what were the steps to register a custom config source that a user writes (i.e. what is this ServiceLoader concept in the MicroProfile Config ConfigSource specification?)

**Comment by radcortez** [comment]
Hi @dzou thanks for reaching out.

Yes, you can use the `ServiceLoader` mechanism to register additional `ConfigSources`. This is specified in the MP Config spec: https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configsources.asciidoc.

Let me know how that goes and if you have any trouble implementing it or using it in Quarkus.

**Comment by dzou** [comment]
Thank you for the references, really appreciate it! I'll give it a shot in the next few days and will let you know.

**Comment by dzou** [comment]
Thanks for the help, this is really great. I got this to work for our secret store: https://github.com/quarkiverse/quarkus-google-cloud-services/pull/78

Closing.

**Comment by dzou** [comment]
Sorry - I just have one followup question.

Is it possible for a `ConfigSourceFactory` to access the beans defined in a Quarkus producer via dependency injection?

I'm writing a Quarkus extension where we have a `Producer` class which provides a Client object that lets me access the secret store. Wondering if there is some way to access the Quarkus dependency injection context via the config source factory. Here is [my reference code](https://github.com/quarkiverse/quarkus-google-cloud-services/blob/a2686e74f125ea7f0b3f2319ba231583646d3291/secret-manager/runtime/src/main/java/io/quarkiverse/googlecloudservices/secretmanager/runtime/config/SecretManagerConfigSourceFactory.java#L33) if you are curious.

**Comment by radcortez** [comment]
Unfortunately no.

Arc users Config to configure itself, so to be able to support bean injection in Config, you get into a chicken / egg problem. You need the Config to startup the bean engine, but you need the bean engine to startup to Config.

What you can do, is to defer the bean lookup when you call something into the `ConfigSource` and retrieve the bean programmatically. You can find an example here: https://github.com/quarkusio/quarkus/blob/master/extensions/vault/runtime/src/main/java/io/quarkus/vault/runtime/config/VaultConfigSource.java

**Comment by dzou** [comment]
Gotcha, I got this working. Thank you very much for the help.
