### ISSUE TITLE
IllegalArgumentException exception in AbstractLocationConfigSourceLoader

### ISSUE THREAD

**Issue by jseths** [smallrye/smallrye-config#492]
If the uri contains illegal character like space, you get a IllegalArgumentException exception here:

https://github.com/smallrye/smallrye-config/blob/b109f5839634cac471e523d07be0d67ef66838d8/implementation/src/main/java/io/smallrye/config/AbstractLocationConfigSourceLoader.java#L245

Need to use `uri.getRawSchemeSpecificPart()` instead of `uri.getSchemeSpecificPart()` because it's return decoded data but `URI.create` need legal characters.

**Comment by radcortez** [comment]
Thanks for reporting the issue. I'll provide a fix.
