### ISSUE TITLE
Use one impl to work with both javax and jakarta namespace

### ISSUE THREAD

**Issue by Emily-Jiang** [smallrye/smallrye-config#527]
In order to support jakarta namespace as well as javax, it might be too much to duplicate the streams just because the namespace changes. I would like to propose to adopt [Eclipse Transformer](https://github.com/eclipse/transformer) to deal with either namespace with the same source and then produce two binaries, one working with javax and the other working with jakarta namespace.

**Comment by Emily-Jiang** [comment]
Some prototype PR will happen in due course.

**Comment by tevans78** [comment]
Work in progress;
JEE9 version of the API - https://github.com/tevans78/microprofile-config/tree/JEE9Version
JEE9 transformer in SmallRye - https://github.com/tevans78/smallrye-config/tree/JEE9Transformed

**Comment by tevans78** [comment]
@radcortez 
Hi Roberto, I have some prototype code that can be used to manually pass a JEE9 version of the TCK. However, I am struggling to automate TCK testing in the smallrye build and I would appreciate some help & suggestions.

This commit (https://github.com/tevans78/smallrye-config/commit/cfcfc19b7fe3fd4d445d79d01b7b3c95cbe5b384) adds the transformer. It is really simple and produces artififacts with a "transformed" maven classifier (please ignore the version qualifiers I added, they're just for my testing).

This commit creates a new `tck-jee9` sub-project (https://github.com/tevans78/smallrye-config/commit/8ee8db21b2f44a0050f67fe14767a6591a2a4ec0). You can see that I have had to override the versions of quite a few dependencies in the pom. Although that does seem a bit messy, I think it should have worked. But when I try to run it, it is still referencing some javax classes. I can't figure out why ... I know the transformed jars will the pass the TCK.
```
Caused by: java.lang.NoClassDefFoundError: javax/annotation/Priority
	at io.smallrye.config.SmallRyeConfigBuilder$InterceptorWithPriority$1.getPriority(SmallRyeConfigBuilder.java:416)
	at io.smallrye.config.SmallRyeConfigBuilder$InterceptorWithPriority.<init>(SmallRyeConfigBuilder.java:424)
	at io.smallrye.config.SmallRyeConfigBuilder$InterceptorWithPriority.<init>(SmallRyeConfigBuilder.java:403)
	at io.smallrye.config.SmallRyeConfigBuilder$InterceptorWithPriority.<init>(SmallRyeConfigBuilder.java:395)
	at io.smallrye.config.SmallRyeConfigBuilder.getDefaultInterceptors(SmallRyeConfigBuilder.java:196)
	at io.smallrye.config.SmallRyeConfig.buildInterceptors(SmallRyeConfig.java:87)
	at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:63)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:373)
	at io.smallrye.config.SmallRyeConfigFactory$Default.getConfigFor(SmallRyeConfigFactory.java:59)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:76)
	at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:101)
	at io.smallrye.config.inject.ConfigExtension.validate(ConfigExtension.java:129)
```

Initially I assumed that it must still be pulling in the untransformed version of the smallrye config jars. I turned on some maven debug with -X and the classpath that gets listed out appears to have the right content;
```
[DEBUG] boot(compact) classpath:  surefire-booter-2.22.2.jar  surefire-api-2.22.2.jar  surefire-logger-api-2.22.2.jar  test-classes  13  microprofile-config-api-3.0-ibm20210323.jar  smallrye-config-2.1.1-ibm20210323-transformed.jar  smallrye-config-core-2.1.1-ibm20210323.jar  jboss-logging-3.4.1.Final.jar  smallrye-config-core-2.1.1-ibm20210323-transformed.jar  smallrye-common-annotation-1.5.0.jar  smallrye-common-expression-1.5.0.jar  smallrye-common-function-1.5.0.jar  smallrye-common-constraint-1.5.0.jar  smallrye-common-classloader-1.5.0.jar  asm-9.0.jar  smallrye-config-common-2.1.1-ibm20210323.jar  jakarta.enterprise.cdi-api-3.0.0.jar  jakarta.el-api-4.0.0.jar  jakarta.interceptor-api-2.0.0.jar  jakarta.inject-api-2.0.0.jar  jakarta.annotation-api-2.0.0.jar  weld-core-impl-4.0.1.Final.jar  weld-spi-4.0.Final.jar  jboss-classfilewriter-1.2.4.Final.jar  weld-api-4.0.Final.jar  arquillian-weld-embedded-3.0.0.Alpha1.jar  arquillian-container-spi-1.7.0.Alpha9.jar  arquillian-core-spi-1.7.0.Alpha9.jar  arquillian-config-api-1.7.0.Alpha9.jar  arquillian-config-impl-base-1.7.0.Alpha9.jar  arquillian-config-spi-1.7.0.Alpha9.jar  shrinkwrap-descriptors-api-base-2.0.0.jar  arquillian-container-test-spi-1.7.0.Alpha9.jar  arquillian-testenricher-cdi-jakarta-1.7.0.Alpha9.jar  microprofile-config-tck-3.0-ibm20210323.jar  hamcrest-all-1.3.jar  shrinkwrap-api-1.2.6.jar  arquillian-testng-container-1.7.0.Alpha9.jar  arquillian-testng-core-1.7.0.Alpha9.jar  arquillian-test-api-1.7.0.Alpha9.jar  arquillian-core-api-1.7.0.Alpha9.jar  arquillian-test-spi-1.7.0.Alpha9.jar  arquillian-container-test-api-1.7.0.Alpha9.jar  arquillian-core-impl-base-1.7.0.Alpha9.jar  arquillian-test-impl-base-1.7.0.Alpha9.jar  arquillian-container-impl-base-1.7.0.Alpha9.jar  shrinkwrap-descriptors-spi-2.0.0.jar  arquillian-container-test-impl-base-1.7.0.Alpha9.jar  shrinkwrap-impl-base-1.2.6.jar  shrinkwrap-spi-1.2.6.jar  testng-7.4.0.jar  jcommander-1.78.jar  jquery-3.5.1.jar  bsh-2.0b6.jar  12  11  10  9  classes  surefire-testng-2.22.2.jar  common-java5-2.22.2.jar  surefire-testng-utils-2.22.2.jar  surefire-grouper-2.22.2.jar
```

I realise that maybe some other smallrye jars might need to be transformed eventually (e.g. smallrye-common-annotation) but I don't think that is the cause of this problem.

**Comment by tevans78** [comment]
@Azquelt has pointed out that the classpath has _both_ `smallrye-config-core-2.1.1-ibm20210323.jar` and `smallrye-config-core-2.1.1-ibm20210323-transformed.jar`. Not sure how that is possible. The pom has this dependency
```
    <dependency>
      <groupId>io.smallrye.config</groupId>
      <artifactId>smallrye-config-core</artifactId>
      <classifier>transformed</classifier>
      <version>2.1.1-ibm20210323</version>
      <scope>test</scope>
    </dependency>
```

**Comment by tevans78** [comment]
So adding the classifier in the tck's pom does not stop other artifacts from pulling in the version without the classifier... need to rethink this.

**Comment by radcortez** [comment]
Yes, if I remember correctly, the classifier is additive and does not override the main dependency because it is completely legal to have both, for instance with the sources or javadoc.

What you can try to do is to exclude the main dependency to force the classpath into using the classifier jar. Or better yet, add it directly and mark it as `provided`.

**Comment by tevans78** [comment]
Separating into a separate artifact looks much better to me; a separate artifact with a separate set of dependencies.
I have drafted a PR against the transformer maven plugin. Using that I was able build everything end to end and run both versions of the TCK. Note that the unit tests are not transformed or run but I don't think that matters because we are not changing the logic of the transformed code.

Here is my PR for the transformer: https://github.com/eclipse/transformer/pull/140
After I get some feedback on that I will create a PR here which uses it.

**Comment by dmlloyd** [comment]
While I appreciate the experimental spirit of what's going on here, I'm quite skeptical of this approach.  It seems highly localized and it's really unclear how it will scale out to entire systems.

In my opinion, we really can't expect systems to be homogenous with respect to `javax` versus `jakarta`.  How do we expect systems to work which have artifacts that consist of a mix of both, as seems inevitable?  The discussions I've seen only seem to propose various implementation solutions, with no consensus.

Has this approach even been discussed at a SmallRye-wide level? The Jakarta and MicroProfile discussions are more or less deadlocked as far as I can tell, and will certainly stay that way until/unless there is a feasible approach that will scale across all the various libraries and frameworks.

**Comment by Emily-Jiang** [comment]
> Has this approach even been discussed at a SmallRye-wide level? The Jakarta and MicroProfile discussions are more or less deadlocked as far as I can tell, and will certainly stay that way until/unless there is a feasible approach that will scale across all the various libraries and frameworks.

The deadlock is to be resolved via some experiment, which is why this issue was opened. The conversation will resume once we have got some rough idea on how to support both namespace. Please see the latest suggestions from me on that thread.

**Comment by arjantijms** [comment]
@Emily-Jiang we're now slowly approaching November. Do we already have a rough idea on how to support both namespaces?

(p.s. In OmniFaces and Mojarra we just created separate branches for javax.* and jakarta.* and merge things between branches whenever necessary)

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang we're now slowly approaching November. Do we already have a rough idea on how to support both namespaces?
> 
> (p.s. In OmniFaces and Mojarra we just created separate branches for javax.* and jakarta.* and merge things between branches whenever necessary)

@arjantijms I can't say much from smallrye point of view. I did propose some PRs for SmallRype to create two branches but @roberto does not want to maintain two branches. For MP 5.0, it is jakarta.* namespace only. In Open Liberty, we used Eclipse Transformer and maintain one codebase.

**Comment by radcortez** [comment]
We are still discussing how we are going to move forward. We should have an answer in the next couple of weeks.

**Comment by arjantijms** [comment]
@radcortez Thanks, very eager to take advantage of some of the small rye components in some projects I'm working with, but we need the jakarta version. I'll keep watching this space.

**Comment by radcortez** [comment]
Sure.

We were exploring some options with the Eclipse Transformer, but it is not really easy to use for libraries. I mean, it works fine, but dealing with transitive dependencies and distribution of the transformed jar is straightforward. We are prototyping and trying out multiple scenarios to see what works best.

**Comment by radcortez** [comment]
Jakarta namespace in https://github.com/smallrye/smallrye-config/tree/jakarta
