### ISSUE TITLE
smallrye.config.mapping.validate-unknown should default to false

### ISSUE THREAD

**Issue by tevans78** [smallrye/smallrye-config#548]
I pulled version 2.2.0 into OpenLiberty and found that unless `smallrye.config.mapping.validate-unknown` was set to `false`, SmallRye Config 2.2.0 did not pass the TCK. Using the default value of `true`, hundreds of validation errors were produced. e.g.
```
Stack Dump = org.jboss.weld.exceptions.DeploymentException: Configuration validation failed:
	PATH does not map to any root
	java.specification.version does not map to any root
	com.ibm.team.repository.transport.client.protocol does not map to any root
	bvt.prop.security_4_HTTP_default does not map to any root
	bvt.prop.controller_3.http does not map to any root
	wlp.workarea.dir does not map to any root
	com.ibm.vm.bitmode does not map to any root
	sun.arch.data.model does not map to any root
	java.vendor.url does not map to any root
	ldap.3.ssl.port does not map to any root
	mp.tck.prop.dummy does not map to any root
	bvt.prop.batch.endpoint_1_HTTP_default does not map to any root
	sun.boot.library.path does not map to any root
	sun.java.command does not map to any root
	bvt.prop.controller_4.replica does not map to any root
	com.ibm.tools.attach.enable does not map to any root
	java.specification.vendor does not map to any root
	java.version.date does not map to any root
	java.home does not map to any root
	org.apache.aries.blueprint.preemptiveShutdown does not map to any root
```
The full list was much longer. Given that the vast majority of these errors are being triggered by properties from the default config sources, having `validate-unknown` default to `true` does not seem like a good idea.

I also note that the error message is not very helpful and I had to dig through the source to find the undocumented property which was causing the problem.

**Comment by Joseph-Cass** [comment]
It looks like this is the code of interest, and that there's still a TODO in there to remove setting the property to `false` : 
https://github.com/smallrye/smallrye-config/commit/3cf4e4b5683b2de92eac4e8c4b07b3b068741290

**Comment by radcortez** [comment]
This is the default behaviour for SR @ConfigMapping in `1.x`. Unfortunately, during the `2.x` the implementation, I disabled the validations to move the implementation forward and I forgot to enabled them back.

I'll prefer if we keep the SR @ConfigMapping behaviour the same and figure out some other way for @ConfigProperties.

**Comment by Emily-Jiang** [comment]
@radcortez It looks that the `validation-unknown` reports a lot of system properties. Are you sure it is only related to `@ConfigProperties`? I think the error message is overwhelming. I am wondering whether it makes sense to turn off the validation by default. I think we are in agreement that setting this property in tck runs is problematic as the default behaviour is different.

**Comment by radcortez** [comment]
What we do with the validation is to make sure that all properties are mapped into a ConfigMapping, but the validation occurs only in the namespace (prefix) being mapped. In the case of the TCK, since we have mappings without any root / prefix the system properties and env variables appear as being unmapped and originate the errors.

This is something that I don't want to disable for the SR ConfigMappings, but we can add something to ignore these if only ConfigProperties are being used.

**Comment by radcortez** [comment]
BTW, I had the idea that Liberty instantiates the Config with a specific `SmallRyeConfigBuilder` (ignoring the default from the Provider / Factory). If that is the case, could `io.smallrye.config.SmallRyeConfigBuilder#withValidateUnknown` help?

**Comment by tevans78** [comment]
We do have a subclass of SmallRyeConfigBuilder where we could call `withValidateUnknown(false)` in the constructor ... but I don't think that @Emily-Jiang wants it done that way. More generally, I think Emily would like SmallRye Config to pass the MicroProfile Config TCK without needing to set any special properties.

**Comment by Emily-Jiang** [comment]
@radcortez I don't think you can claim compliance with a switch to flip the default behaviour. For end users, they will get a different behaviour out of box.

**Comment by radcortez** [comment]
Ok, let me think about this.
