### ISSUE TITLE
Error in trying to implement HOCON Config Source for Quarkus

### ISSUE THREAD

**Issue by nweike** [smallrye/smallrye-config#593]
Hello ,
I am trying to configure my Quarkus application to use HOCON file format for its ConfigSource implementation .

Here are the steps that i took:

1) Add below in my pom.xml:

<dependency>
    <groupId>io.smallrye.config</groupId>
    <artifactId>smallrye-config-source-hocon</artifactId>
    <version>1.10.0</version>
</dependency>

2) created a file with with the following content  and saved it in META-INF  folder as microprofile-config.conf

{
"accepted.counties":
[
{"name": "Fiji", "code": "FJ"},
{"name": "Finland", "code": "FI"},
{"name": "France", "code": "FR"},
{"name": "French Guiana", "code": "GF"},
{"name": "French Polynesia", "code": "PF"},
{"name": "French Southern Territories", "code": "TF"},
{"name": "Gabon", "code": "GA"},
{"name": "Gambia", "code": "GM"}
]}

 I am getting com.typesafe.config.ConfigException$WrongType, "accepted.counties" has type LIST rather than STRING 

What step I am getting wrong?

Kind Regards,
Nweike

**Comment by gaol** [comment]
I think it is because only [ConfigSyntax.CONF](https://github.com/smallrye/smallrye-config/blob/1110d8022dd9ed6af233b3d10c1789f00b0f7454/sources/hocon/src/main/java/io/smallrye/config/source/hocon/HoconConfigSourceProvider.java#L19) is supported ?

**Comment by radcortez** [comment]
The issue seems to be here:
https://github.com/smallrye/smallrye-config/blob/c2b3707e1dd6d90b9d3ed367e415bb43e4f7c320/sources/hocon/src/main/java/io/smallrye/config/source/hocon/HoconConfigSource.java#L16

All values are being read as Strings. Let me see what I can do.

@nweike do you have more complex examples that I can use to try and test?

**Comment by nweike** [comment]
Hello @radcortez ,
Right now my use case is any json object. Right now, i am passing a json array . I think that's is as complicated as it gets

**Comment by radcortez** [comment]
Ok. Thank you!

Do you mind if I ask what do you prefer to use a HOCON source instead of the properties ones or even yaml? Do you want to have your configuration in json?

**Comment by radcortez** [comment]
@nweike Please check #599. Most likely we still need some more work there, but at least lists should be working.
