### ISSUE TITLE
Add built-in support for non-object Optional* types

### ISSUE THREAD

**Issue by dmlloyd** [smallrye/smallrye-config#60]
The types `OptionalInt`, `OptionalLong`, and `OptionalDouble` provide a better means to abstract an optional primitive value than boxed types.  It would be nice if it were possible to use these types from `Config`.

Registering a custom `Converter` in conjunction with `Config#getValue` is not sufficient, because converters are only called when a `String` value is present in the configuration.  Using `getOptionalValue` is unwieldy because the result would be of type `Optional<OptionalInt>` or similar.

**Comment by kenfinnigan** [comment]
Resolved with #62
