### ISSUE TITLE
Property expressions are not supported by methods in Config neither in injected properties

### ISSUE THREAD

**Issue by NicoNes** [smallrye/smallrye-config#601]
According to my understanding of the spec, Property expressions must be supported by all method from the `Config` class:

> Property expressions applies to all the methods in Config that performs resolution of a configuration property, including getValue, getValues, getConfigValue, getValues, getOptionalValue, getOptionalValues and getConfigProperties. 

So I was expecting following line of code to work but it fails with `java.util.NoSuchElementException: SRCFG00014: The config property ${jaxrs-ext.version} is required but it could not be found in any config source`:

`ConfigProvider.getConfig().getValue("${myProperty}", String.class);`

Its the same when using property  expression in injected property configuration. The spec says:

> Property expressions must also be applied to configuration properties injected via CDI. A default value defined via org.eclipse.microprofile.config.inject.ConfigProperty#defaultValue is not eligible to be expanded since multiple candidates may be available.

But following fails with : `SRCFG02000: Failed to Inject @ConfigProperty for key {myProperty} into org.nne.jaxrs.ext.core.samples.gettingstarted.EchoResource.myProperty since the config property could not be found in any config source`

```
@Inject
@ConfigProperty(name = "myProperty")
private String myProperty;
```

Am I missing soemthing ?

Thanks

**Comment by dmlloyd** [comment]
In your first example, the error occurs because the property `jaxrs-ext.version` was used in an expression, but that property wasn't defined.  If you want the expression to expand to an empty string in this case, use the string `${jaxrs-ext.version:}` (note the `:` near the end).

In your second example, you're trying to get the value of a property whose name is given in another property called `myProperty`.  If you just want the value of `myProperty`, use `ConfigProvider.getConfig().getValue("myProperty", String.class)` instead.

In the final example, the property `myProperty` is likely missing, resulting in an error.

**Comment by NicoNes** [comment]
@dmlloyd Thanks. The code snippet of my first example was wrong and the others were too simple so it seems you did not get my point.
Let me change examples to make it clear. My `microprofile-config.propertie` looks like:

```
property1=Hello
property2=world
```

 Based on my spec understanding :

- I was expecting following line of code to work. But it fails with `SRCFG00014: The config property ${property1} ${property2} is required but it could not be found in any config source`:

`ConfigProvider.getConfig().getValue("${property1} ${property2}", String.class);`

- I was expecting following line of code to work. But it fails with `RCFG02000: Failed to Inject @ConfigProperty for key ${property1} ${property2} into org.nne.jaxrs.ext.core.samples.gettingstarted.EchoResource.myProperty since the config property could not be found in any config source`:

```
	@Inject
	@ConfigProperty(name = "${property1} ${property2}")
	private String myProperty;
```

My point with those examples is about supporting property expression in methods from `Config` class and in configuration properties injected via CDI.

**Comment by radcortez** [comment]
Hi @NicoNes,

Maybe the spec text is not completely clear, but what gets expanded is the value (or values) of a property lookup and not the property itself, meaning that the expression syntax is not applied in property names but only property values.

A call to any of the lookup methods must always resolve to a specific property name. For instance:

```properties
foo=${bar}
bar=bar
```

```java
getValue("foo", String.class) // gives the value "bar"
```

**Comment by NicoNes** [comment]
Hi @radcortez,

OK it makes sense like that, thank you.
Yes the spec text is not clear on this point. 
Maybe those two misleading paragraph should be removed of the spec since the beahvior they described and that you explained above seems obvious, no really need to mention it.

I will close the issue.

Thanks

**Comment by radcortez** [comment]
Thanks! Please, feel free to send an update in the spec project.
