### ISSUE TITLE
CDI programmatic lookup failed for beans  annotated with @ConfigProperties qualifier 

### ISSUE THREAD

**Issue by NicoNes** [smallrye/smallrye-config#602]
Hi guys,

Let's consider this CDI bean:

```
@ConfigProperties(prefix = VersionConfigProperties.PROPERTIES_PREFIX)
public class VersionConfigProperties {

	static final String PROPERTIES_PREFIX = "application";

	public static final String VERSION_PROPERTY = PROPERTIES_PREFIX + ".version";
	public static final String BUILD_TIME_PROPERTY = PROPERTIES_PREFIX + ".buildTime";

	private String version;
	@ConfigProperty(name = "buildTime")
	private String buildTime;

	public String getVersion() {
		return this.version;
	}

	public String getBuildTime() {
		return this.buildTime;
	}

}
```
Using CDI programmatic lookup `CDI.current().select(VersionConfigProperties.class, ConfigProperties.Literal.of("prefix")).get()` failed when no injection point prefixed with `prefix` exist.

Following case failed:

```
@Path("EchoResource ")
@Produces({ MediaType.TEXT_PLAIN })
public class EchoResource {

       @GET
	public Response echo() {
		CDI.current().select(VersionConfigProperties.class, ConfigProperties.Literal.of("prefix")).get(); //=> failed
		return Response.ok().buikd();
	}
```

Following case succeed:

```
@Path("EchoResource ")
@Produces({ MediaType.TEXT_PLAIN })
public class EchoResource {

      @Inject
      @ConfigProperties(prefix = "prefix")
       private VersionConfigProperties versionConfigProperties;

       @GET
	public Response echo() {
		CDI.current().select(VersionConfigProperties.class, ConfigProperties.Literal.of("prefix")).get(); //=> succeed
		return Response.ok().buikd();
	}
```

I was expecting both cases to work. Am I wrong ?

Thanks

**Comment by radcortez** [comment]
The spec is not clear in this case. What we know is that the spec mandates that the configuration values are validated and may be converted, so in the case of `@ConfigProperties` we eagerly do the work, to make sure that they can be injected and all values converted or you get a `DeploymentException`.

In my opinion, if we allow a programmatic CDI lookup with any prefix, you can't do that, meaning that in some cases you will get a `DeploymentException` (when we are able to validate beforehand) and some other exception on the programmatic CDI lookup, making the API behaviour somehow inconsistent.

**Comment by NicoNes** [comment]
> In my opinion, if we allow a programmatic CDI lookup with any prefix, you can't do that, meaning that in some cases you will get a DeploymentException (when we are able to validate beforehand) and some other exception on the programmatic CDI lookup, making the API behaviour somehow inconsistent.

Sorry I do not see the inconsistency you're talking about because in my opinion, that's already what happen for any CDI bean : when a bean is injected via `@Inject` and the validation failed a `DeploymentException` is thrown and when a bean is looked up programmatically but cannot be found an `UnsatisfiedResolutionException` is thrown right ?

In my opinion the MP config spec does not need to say more about CDI programmatic lookup with any prefix.
I'm not a CDI expert but for what I've seen so far, every bean that can be injected via `@Inject` can also be retrieved programmatically.
The current behavior I spotted out and described above is inconsistent with this CDI "rule" and more the fact that programmatic lookup for a given prefix (other than the one on the ConfigProperties class) only works when injection via `@Inject` exist in the code make us feel like the `@Inject` acts like a CDI bean `Producer`.

**Comment by Emily-Jiang** [comment]
> > In my opinion, if we allow a programmatic CDI lookup with any prefix, you can't do that, meaning that in some cases you will get a DeploymentException (when we are able to validate beforehand) and some other exception on the programmatic CDI lookup, making the API behaviour somehow inconsistent.
> 
> Sorry I do not see the inconsistency you're talking about because in my opinion, that's already what happen for any CDI bean : when a bean is injected via `@Inject` and the validation failed a `DeploymentException` is thrown and when a bean is looked up programmatically but cannot be found an `UnsatisfiedResolutionException` is thrown right ?
> 
> In my opinion the MP config spec does not need to say more about CDI programmatic lookup with any prefix.
> I'm not a CDI expert but for what I've seen so far, every bean that can be injected via `@Inject` can also be retrieved programmatically.
> The current behavior I spotted out and described above is inconsistent with this CDI "rule" and more the fact that programmatic lookup for a given prefix (other than the one on the ConfigProperties class) only works when injection via `@Inject` exist in the code make us feel like the `@Inject` acts like a CDI bean `Producer`.

The programmatic look up and injection matches with CDI rules. According to CDI spec, all injection points would be validated. Therefore, for injection case, you might get DeploymentException. For programmatic lookup, it will only look up for the beans during runtime, so you will get runtime exception, which is UnsatisfiedResolutionException. I don't see why it is inconsistent with CDI rules.

**Comment by radcortez** [comment]
In reality the MP Config spec has a major flaw, which is the mix of the programmatic API and CDI (meaning that you can use MP Config without a CDI container). This causes some major inconsistencies between the Config programmatic API and the CDI own programmatic API.

In our own programmatic API, we validate that all configuration properties exist and we can only do that by knowing beforehand which prefixes should be validated. This is either retrieved from the annotation, or additional prefixes may be registered with the Config object. For CDI, we follow the same process and piggyback on the programmatic objects, but now we need to turn them into CDI beans...

It is possible to dynamically perform the lookup, but I prefer if we do not support that. The entire dynamic nature of configuration makes debugging really hard, and the presence of a single key (or not) is the difference between a successful lookup or a failure (and the key may also change in time). So, having everything validated on start is usually better to avoid these runtime errors.

My advice is to just set the prefix in the properties class. If you have multiple prefixes, then the injection point override also works. Finally, if you really want to use the CDI lookup, you can bootstrap your own builder with the `SmallRyeConfigFactory` and register additional mappings / prefixes there.

If any of these does not convince you, we happily accept pull-requests :)

**Comment by NicoNes** [comment]
@radcortez I had a look to SmallryeConfig code and I understand your explaination well about the dynamic lookup.
Actually using override at injection point is fine for me. I will close the issue.

I created this issue because of the config spec text at https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#_programmatic_lookup_of_the_bean_annotated_with_code_configproperites_code taht says that we can use CDI programmatic lookup since the class with @ConfigProperties is a bean.
More when I saw that `org.eclipse.microprofile.config.inject.ConfigProperties.Literal` provides a method to get a literal for a given prefix I thought CDI programmatic lookup for any given prefix will work.

I don't know if the spec must clarify this point or if this behavior is just smallrye specific, I let you decide guys.

Thanks

**Comment by Emily-Jiang** [comment]
> In reality the MP Config spec has a major flaw, which is the mix of the programmatic API and CDI (meaning that you can use MP Config without a CDI container). This causes some major inconsistencies between the Config programmatic API and the CDI own programmatic API.

By the way, this is not a flaw. The use case is to allow CDI extension using programmatic API to look up config properties before CDI container is fully up. As a matter of fact, config SPIs can be used when CDI is not present, which is why they are in different packages.

**Comment by radcortez** [comment]
> > In reality the MP Config spec has a major flaw, which is the mix of the programmatic API and CDI (meaning that you can use MP Config without a CDI container). This causes some major inconsistencies between the Config programmatic API and the CDI own programmatic API.
> 
> By the way, this is not a flaw. The use case is to allow CDI extension using programmatic API to look up config properties before CDI container is fully up. As a matter of fact, config SPIs can be used when CDI is not present, which is why they are in different packages.

I didn't say I'm against CDI using Config, but in my opinion it is flawed. For instance one issue that ConfigProperties introduced is that we cannot have a truly immutable Config instance, since you need a Config instance for CDI, but only when you get to CDI is when you have the complete information on how to create such objects.

**Comment by Emily-Jiang** [comment]
> > > In reality the MP Config spec has a major flaw, which is the mix of the programmatic API and CDI (meaning that you can use MP Config without a CDI container). This causes some major inconsistencies between the Config programmatic API and the CDI own programmatic API.
> > 
> > 
> > By the way, this is not a flaw. The use case is to allow CDI extension using programmatic API to look up config properties before CDI container is fully up. As a matter of fact, config SPIs can be used when CDI is not present, which is why they are in different packages.
> 
> I didn't say I'm against CDI using Config, but in my opinion it is flawed. For instance one issue that ConfigProperties introduced is that we cannot have a truly immutable Config instance, since you need a Config instance for CDI, but only when you get to CDI is when you have the complete information on how to create such objects.

I don't see why ConfigProperties forced the immutable config instance. You will create a Config instance first. ConfigProperties is just to retrieve values from the built Config.
