### ISSUE TITLE
Does @ConfigMappings support Class as well? 

### ISSUE THREAD

**Issue by koalalam** [smallrye/smallrye-config#620]
As captioned - the use case is that there are configuration POJOs provided by 3rd party libs and we want to simply re-use them.

For example:

```
@ConfigMapping(prefix = "server")
public class Server {
    private String host;
    private int port;

    public String getHost() {
        return host;
    }

    public void setHost(String host) {
        this.host = host;
    }

    public int getPort() {
        return port;
    }

    public void setPort(int port) {
        this.port= port;
    }
}
```

**Comment by radcortez** [comment]
In my opinion, supporting such cases raises too many questions and creates consistency issues.

With an interface, your contract is well defined. We pick the abstract methods and we generate their implementation. With a class, things become more tricky. Where do we look? Fields or methods? What if a method exists without an associated field? Do we subclass to generate an implementation or silently ignore it? What about private fields? Yes, we could change them with reflection, but depending on the case it may not work in future Java versions. In the end, I believe that it was not worth implementing the support for little benefit.

Now, we do support MP `@ConfigProperties` which is class-based, but with some limited functionality (no nested classes, no composed elements, etc). Maybe it will be enough for your use case. I'm advocating to remove the class support and replace it with interface in the MP specification.

If you still think that such support should be added, we are always open to accepting pull-requests :)
