### ISSUE TITLE
website "edit this page" links points to master instead of main

### ISSUE THREAD

**Issue by maxandersen** [smallrye/smallrye-config#622]
ie. https://smallrye.io/docs/smallrye-config/index.html points to https://github.com/smallrye/smallrye-config/edit/master/doc/modules/ROOT/pages/index.adoc which is a 404

should be https://github.com/smallrye/smallrye-config/edit/main/doc/modules/ROOT/pages/index.adoc

**Comment by radcortez** [comment]
Thanks for spotting this. Apparently Antora still uses `master` to define the no version documentation: https://docs.antora.org/antora/2.3/component-with-no-version/. It should be fixed now.
