### ISSUE TITLE
missing docs on how to actually use smallrye config standalone

### ISSUE THREAD

**Issue by maxandersen** [smallrye/smallrye-config#623]
been looking at smallrye config docs and eclipse microprofile config but nowhere do I seem to find how to actually use the api ? 

just docs about how to write the config files.

is there a primer/getting started guide somewhere google doesn't know about ?

**Comment by radcortez** [comment]
It's here: https://microprofile.io/project/eclipse/microprofile-config/spec/src/main/asciidoc/microprofile-config-spec.asciidoc.

But it seems this is not being indexed. We usually only document SR Config specific features in our docs to avoid duplication, but maybe we should add everything to have a single source that people can go to. What do you think?

**Comment by maxandersen** [comment]
Not sure what it is but It's at least not readable on mobile :)

**Comment by radcortez** [comment]
It's the MP Config specification. The website should generate the proper page from the asciidoc, but maybe it doesn't work for mobile.
