### ISSUE TITLE
Config.getValueCollection()

### ISSUE THREAD

**Issue by dmlloyd** [smallrye/smallrye-config#63]
It would be great if the base `Config` interface had methods to get collections of single-valued items.  The API could accept a function that accepts a size estimate and yields some kind of collection type.

I'll send up a PR as an example of how the API could look, if added on `SmallRyeConfig`.

**Comment by jmesnil** [comment]
+1

The `Config` API only allows programmatic lookup of arrays (
https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/converters.asciidoc#array-converters)  while the CDI injection supports array, `List` and `Set`.
