### ISSUE TITLE
Map of Map not supported in SmallRye ConfigMapping

### ISSUE THREAD

**Issue by radcortez** [smallrye/smallrye-config#667]
From https://github.com/quarkusio/quarkus/issues/19091

**Comment by aneira** [comment]
Question, do you still not support maps?
To use depending on the value of serviceName and get the values ​​according to the service.

Map<String, String> parameters = dataMappingConfig.services().get(serviceName);


@ConfigMapping(prefix = "mapping-service")
public interface DataMappingConfig {

    Map<String, Map<String, String>> services();
}

Yaml
mapping-service:
  service1:
      id-type: "DNI"
      id-number: "12345"
  service2:
      id-type: "DNI"
      id-number: "12345"

**Comment by radcortez** [comment]
Yes, this works, but you need to annotate `services()` with `@WithParentName` or adjust the configuration to include a `services` segment.

Your mapping definition expects to find the configuration at `mapping-services.services.[map-key].[map-key]`.
