### ISSUE TITLE
Support AutoCloseable on ConfigSourceFactory

### ISSUE THREAD

**Issue by brianwyka** [smallrye/smallrye-config#675]
If a `ConfigSourceFactory` needs to cleanup resources it would be nice to support a `close` method which will be called during this phase.

```java
public interface ConfigSourceFactory extends AutoCloseable {

  @Override
  default void close() {

  }

}
```

Is there any hook for this "destruction" phase currently?

I see that `ConfigSource` supports this:
https://github.com/eclipse/microprofile-config/blob/4bda7c776e00a3baf41af728215900e02485de2c/api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java#L100

**Comment by radcortez** [comment]
The `ConfigSourceFactory` is actually short-lived, it only acts as a wrapper to be able to access the Config, while being created to configure the factory sources. After the init is done they are discarded.

I don't see a reason to hold state in the factory that needs to be clean. All resources lookup and cleanups can be done in `Iterable<ConfigSource> getConfigSources(ConfigSourceContext context)`.  

Can you please provide an example of how you are implementing the factory to require the `close` method?

**Comment by brianwyka** [comment]
Yes, I think you have a point @radcortez.  I realized this after I opened it.  I think it makes sense to leave it to the `ConfigSource`
