### ISSUE TITLE
Spec issue: ConfigSource.getProperties()

### ISSUE THREAD

**Issue by dmlloyd** [smallrye/smallrye-config#70]
Implementing `ConfigSource.getProperties()` is a far more onerous burden than the rest of the `ConfigSource` API.  In some cases this can be a simple view of an existing map (like system properties), but in other cases one must implement an entire custom `Map` implementation, which can require as many as 7 classes to implement (the Map, its key set & iterator, its value collection & iterator, and its entry set & iterator).  A simple property-expanding decorator requires 5 classes to implement its map view.

The spec currently implements the far simpler `getPropertyNames` method in terms of the abstract `getProperties` method, however it would have been more convenient had the spec done it the other way around.

It might be worthwhile to provide a `Map` implementation which is backed by the `ConfigSource` `getPropertyNames` and `getValue` methods.

**Comment by jmesnil** [comment]
This issue is a good argument to work on https://github.com/eclipse/microprofile-config/issues/333 to update the ConfigSource API to simplify the requirements from the implementation.

**Comment by dmlloyd** [comment]
Solved by #72.
