### ISSUE TITLE
Jakarta EE 9 support

### ISSUE THREAD

**Issue by sergey-morenets** [smallrye/smallrye-config#707]
Hi

Do you have any plans to support Jakarta EE 9(9.1)? The latest Microprofile version (5.0) is already based on Jakarta EE 9.
However I noticed that even the latest SmallRye Config is still Microprofile 2.0 compatible and uses some javax.* types. 
So that prevents us to fully migrate our project to Jakarta EE 9 and get rid of earlier versions.

Thanks.

**Comment by radcortez** [comment]
Hi @sergey-morenets,

There is already an SR Config release that is MP5.0 / Jakarta compatible:
https://search.maven.org/artifact/io.smallrye.config/smallrye-config/3.0.0-RC1/jar

The work is another branch:
https://github.com/smallrye/smallrye-config/tree/jakarta

**Comment by sergey-morenets** [comment]
Thank you, @radcortez 

Do you have any dates for GA release?

**Comment by radcortez** [comment]
No final date yet (but it should happen in Q1). Right now, we are still in the process of releasing RC's of all SmallRye components, to make sure everything is ok.

Is there any issue from your side to use an RC?

**Comment by sergey-morenets** [comment]
Unfortunately we don't use RCs for the production

**Comment by radcortez** [comment]
Ok. Let me see if I can speed this up for you.

**Comment by radcortez** [comment]
There is a `3.0.0` available now.
