### ISSUE TITLE
HOCON config is not resolved

### ISSUE THREAD

**Issue by apatrida** [smallrye/smallrye-config#753]
When using HOCON and expressions, they are considered by typesafe-config as being items that need resolved in that layer and therefore error out when attempting to read or resolve them in the smallrye-config.  How is this intended to work?

**Comment by apatrida** [comment]
Expressions in HOCON such as:

```
{
   foo: "bar",
   expression: ${foo}
}
```

cause config loading to fail because the configuration is not resolved via a call to `config.resolve()` in Typesafe Config.

They must be quoted to be ignored by Typesafe Config:

{
   foo: "bar",
   expression: "${foo}"
}

And then will be resolved at read time by the consumer of the config.

This should be clearly documented because expressions therefore work very differently in Smallrye Config vs. Typesafe Config.

**Comment by radcortez** [comment]
Well, yes. You have the expressions by HOCON which are local to its source and then the expressions by SmallRye Config, which work globally. 

So, any expression defined in the HOCON source needs to be resolved also by HOCON to follow its own rules. 

Are you looking to define expressions in HOCON to be resolved by SmallRye Config?

**Comment by apatrida** [comment]
I don't think `resolve` is ever correctly called for a HOCON expression to function, it will just error out and never work.  There is no way to use them.

So my issue is that nothing is said in the docs "do not use HOCON expressions unquoted because we do not support them" and there is no advice to therefore quote your expressions so they are passed through to SmallRye Config for processing on read.

This topic is not addressed and every user is left to their own to figure out this problem.

**Comment by radcortez** [comment]
We certainly need to improve the documentation on that topic. Are you interested in submitting a PR?

I'm also trying to understand how are you using this to see if we can do something about it.
