### ISSUE TITLE
ConfigSourceFactory seems to be only used at buildtime when using GraalVM

### ISSUE THREAD

**Issue by manofthepeace** [smallrye/smallrye-config#755]
This is somewhat related to https://github.com/smallrye/smallrye-config/issues/752

It may be by design, but would like to confirm. If so I think some documentation around this behaviour would be nice.

After  more testing of the ConfigSourceFactory, looks like it is not called at runtime when using GraalVM.

When running with the openJDK as a jar I can see the ConfigSourceFactory called twice, once at buildTime, and once at runtime.

When compiling to a native executable, I see it only called at buildtime. Meaning if I override, in my case a config flag using env, the ConfigSourceFactory wont run with the runtime value, which ultimately gives me the wrong value at runtime since the config source used the value that was set in the application.properties, and not the one I overwrote using env.

**What I have**

The value from the configSourceFactory is present in;
PropertiesConfigSource[source=Specified default values] with ordinal: -2147483548 with the value used at buildtime

**What I expected**
The configSourceFactory should have created the configsource with the ordinal provided at runtime, using the runtime value for existing configs

`return Collections.singletonList(new PropertiesConfigSource(propMap, "feature-flags", 500));`

in the end I have no "feature-flags" configsource, when building native

**Comment by manofthepeace** [comment]
Yes, this is using quarkus.

**Comment by manofthepeace** [comment]
@radcortez  would this be better suited in the quarkus issues?

**Comment by radcortez** [comment]
This is a Quarkus thing since SR Config does not know build time / runtime config. Please open the issue in Quarkus with a reproducer. Thanks!

**Comment by manofthepeace** [comment]
I tried with latest quarkus for now (2.10.3) and looks like it works OK. Not sure what happened or if it got fixed between May and now. Thanks.

**Comment by radcortez** [comment]
Great :)
