### ISSUE TITLE
Programmatic injection of @ConfigProperties does not work in all cases

### ISSUE THREAD

**Issue by JHahnHRO** [smallrye/smallrye-config#860]
In `io.smallrye.config.inject.ConfigPropertiesInjectionTest#select` there are the two following programmatic selections:
```
Server server = CDI.current().select(Server.class, ConfigProperties.Literal.of(UNCONFIGURED_PREFIX)).get();
```
and
```
Server cloud = CDI.current().select(Server.class, ConfigProperties.Literal.of("cloud")).get();
```
The first one works, because `UNCONFIGURED_PREFIX` is a special case. The second only works, because there is also a field injection point with the qualifier `@ConfigProperties("cloud")` in the same class which is picked up by `ConfigExtension` and for which a suitable synthetic bean is registered.

However, using programmatic injection with a prefix that does not appear in static code (e.g. because it is only computed at runtime) will fail, because `ConfigExtension` removes the `@NonBinding` annotation from the `@ConfigProperties` qualifier (apparently to fix some strange behaviour of OpenWebBeans) and registers synthetic beans only for each particular instance of `@ConfigProperties` it can find during initilization.

More to the point: Adding a third programmatic selection like so
```
Server otherServer = CDI.current().select(Server.class, ConfigProperties.Literal.of("otherServer")).get();
```
to the same test method will make the test fail, even if the corresponding properties exist, because the prefix "otherServer" cannot be found during container initialization. In my mind, this is a violation of the MP Config Spec. At least the spirit, if not the letter of the spec.

I'm not sure what the precise issue with OpenWebBeans is/was, but I think there needs to be a different work around (or maybe OWB needs to fix that on their end)

**Comment by radcortez** [comment]
Closing due to https://github.com/eclipse/microprofile-config/issues/762
