### ISSUE TITLE
Enhancements for @RegexFilter in Events

### ISSUE THREAD

**Issue by brianwyka** [smallrye/smallrye-config#868]
Is it possible to use the `@RegexFilter` to have a method associated with a config event to be called once based on the changed properties if the method takes in a map as an argument?

Current way of handling:
```java
@RegexFilter(onField = Field.key, value = "^quarkus.log\\..+")
void handleLoggingChange(@Observes final ChangeEvent changeEvent) {
   // handle change event
}
```
This results in the `handleLoggingChange` method being invoked multiple times (for as many configurations under `quarkus.log` that have changed).

Potential future way of handling:
```java
@RegexFilter(onField = Field.key, value = "^quarkus.log\\..+")
void handleLoggingChanges(@Observes final Map<String, ChangeEvent> changeEvents) {
   // handle change events
}
```

The `Map` key would be the confit item key (`Field.key`).

**Comment by brianwyka** [comment]
@phillip-kruger, looks like you did most of this work.  Thoughts on feasibility, or is there another way to do this already that I am missing?

**Comment by radcortez** [comment]
We have no plans to enhance CDI features. Our main focus is config as a standalone library.

Of course, PRs are always welcome.
