### ISSUE TITLE
Default methods should not require a java doc

### ISSUE THREAD

**Issue by HerrDerb** [smallrye/smallrye-config#896]
When having a @ConfigMapping with a default method, the annotations processing tells me, that I need to add a javadoc to the default method, as usual for property defining abstract interface method

![image](https://user-images.githubusercontent.com/7398256/220856238-96786cd6-799f-4fac-b41b-5bce97a7b474.png)

This does not make much sense. Default methods should be excluded from this check.

**Comment by radcortez** [comment]
Correct. I'll fix it.

In the meanwhile, you can use `@Deprecated` as a workaround to ignore it (yes ugly I know).

**Comment by radcortez** [comment]
https://github.com/quarkusio/quarkus/pull/31384 will fix this.

I am closing this issue because this is on the Quarkus side, not the SmallRye Config side.
