### ISSUE TITLE
Environment variables mapping rules are not implemented

### ISSUE THREAD

**Issue by pjurczen** [smallrye/smallrye-config#908]
Specification says that environment variables will be searched with following rules, given property name (e.g. com.ACME.size):

1. Exact match (i.e. com.ACME.size)

1. Replace each character that is neither alphanumeric nor _ with _ (i.e. com_ACME_size)

1. Replace each character that is neither alphanumeric nor _ with _; then convert the name to upper case (i.e. COM_ACME_SIZE)

https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#default_configsources.env.mapping

At the moment only exact matches are working, requesting property value using eg. uppercase or underscore instead of exact match doesn't work at all.

**Comment by radcortez** [comment]
Hi @pjurczen,

Can you please provide a reproducer that shows the issue?

We run tests that should cover these scenarios:
https://github.com/smallrye/smallrye-config/blob/b62521ac2cf2d051784482151604c6f25447b0d2/implementation/src/test/java/io/smallrye/config/EnvConfigSourceTest.java

We also run the MicroProfile Config TCK, which we pass, that has tests for these rules.

**Comment by pjurczen** [comment]
Hi @radcortez,

thanks for a quick response. In my case we initialized the property using Openlibery boostrap properties, which resulted in the property landing in SysPropConfigSource. I guess the specification doesn't mention implementing mapping rules for system properties, that's a shame tho.

**Comment by radcortez** [comment]
Yes, we only consider the rules in the `EnvConfigSource`, which reads values coming from `System.getenv()`.

I guess that you could supply your own source based on `EnvConfigSource` and the properties coming from Liberty to provide the mapping env rules.
