### ISSUE TITLE
Add converter for java.nio.Path

### ISSUE THREAD

**Issue by jpraet** [smallrye/smallrye-config#909]
I initially thought `java.nio.Path` would be supported out-of-the-box, given the automatic fallback to a static .of() method that takes a String argument.

But it does not work:
`SRCFG02007: No Converter registered for interface java.nio.file.Path`

It's probably because https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/Path.html#of(java.lang.String,java.lang.String...) takes the additional String... vararg argument.

I think the usecase of injecting a java.nio.Path value may be common enough to warrant an out-of-the-box converter?

**Comment by radcortez** [comment]
We could.

Would you like to submit a PR with it? :)
