### ISSUE TITLE
SmallRye Config Relocate/Fallback causing null value

### ISSUE THREAD

**Issue by ismailsimsek** [smallrye/smallrye-config#916]
When using Relocate or Fallback interceptor im getting null pointer exception
this is what i observed
while the new config name(relocated name) is available its value returned as null. not correctly set
```java
Config config = ConfigProvider.getConfig();
configvalue = config.getConfigValue("OldConfigName").getValue();
null = config.getConfigValue("new-relocated-config-name").getValue();
```

the issue is here
[ SmallRye Config Relocate/Fallback causing nullpointer exception #1 ](https://github.com/ismailsimsek/debezium-server/pull/1)

**Comment by radcortez** [comment]
The Relocate and Fallback interceptors are only one-way mappings, meaning that if you want to use either name and always find a value, you need to use both Relocate and Fallback.

In this example there is Fallback between `.allowPublicKeyRetrieval` and `.allow-public-key-retrieval`. This means that a lookup to `.allowPublicKeyRetrieval`, will first try to use the value, and if it doesn't find any it fallbacks to `.allow-public-key-retrieval` value. A lookup `.allow-public-key-retrieval` will only look at the value on that name and that is it.

You could add a Relocate from `.allow-public-key-retrieval` to `.allowPublicKeyRetrieval` to get the effect you are looking for.
