### ISSUE TITLE
Support for multiple @ConfigMapping interfaces for same prefix

### ISSUE THREAD

**Issue by nielspardon** [smallrye/smallrye-config#944]
I have a use case where I'm using the Quarkus `@LookupIfProperty` annotation to lookup different beans based on the value of a config parameter. Now I would like to use different `@ConfigMapping` interfaces for each of the different beans.

Unfortunately it seems one can only have one `@ConfigMapping` interface per prefix active and one gets a NullPointerException for any additional ones. (Would be great if there was a warning in the logs.)

Example:

config A:
```
connection.type=file
connection.path=/tmp/abc.ext
```

```java
@ConfigMapping(prefix = "connection")
public interface FileConnectionConfiguration {
  String path();
}
```

```java
@LookupIfProperty(
    name = "connection.type",
    stringValue = "file")
@ApplicationScoped
public class FileConnection implements Connection {
  @Inject FileConnectionConfiguration config;
  ...
}
```

config B:
```
connection.type=s3
connection.region=
connection.access-key=
connection.secret-key=
```

```java
@ConfigMapping(prefix = "connection")
public interface S3ConnectionConfiguration {
  String region();
  String accessKey();
  String secretKey();
}
```

```java
@LookupIfProperty(
    name = "connection.type",
    stringValue = "s3")
@ApplicationScoped
public class S3Connection implements Connection {
  @Inject S3ConnectionConfiguration config;
  ...
}
```

**Comment by dmlloyd** [comment]
This is expected to work, so I think it is safe to conclude that this is a bug (regression I think?).

**Comment by radcortez** [comment]
Great :)
