### ISSUE TITLE
Website has faulty installation instructions for gradle and jbang

### ISSUE THREAD

**Issue by bulldog98** [smallrye/smallrye-config#950]
On https://smallrye.io/smallrye-config/Main/#use-smallrye-config-in-a-java-application it looks like this
![grafik](https://github.com/smallrye/smallrye-config/assets/314259/8ad6ce1c-4b1f-4962-b357-1dd17ed38c18)

My guess is that the generation for that site is referencing variable with an incorrect name.

**Comment by radcortez** [comment]
Thanks for the finding the issue :)
